"""Memory-related models for cross-session learning memory."""
from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy import JSON as JSONB, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class SessionSummary(Base):
    """Structured summary of a completed learning session.

    Generated by LLM at session close and persisted for cross-session
    memory injection into the AI teacher's prompt.
    """

    __tablename__ = "session_summaries"
    __table_args__ = (
        {"extend_existing": True},
    )

    id: Mapped[UUID] = mapped_column(
        Uuid(), primary_key=True, default=uuid4
    )
    session_id: Mapped[UUID] = mapped_column(
        Uuid(),
        ForeignKey("learning_sessions.id", ondelete="CASCADE"),
        unique=True,
    )
    student_id: Mapped[UUID] = mapped_column(
        Uuid(),
        ForeignKey("users.id", ondelete="CASCADE"),
        index=True,
    )

    summary_text: Mapped[str] = mapped_column(Text, nullable=False)

    topics_discussed: Mapped[list] = mapped_column(JSONB, default=list)
    knowledge_points_touched: Mapped[list] = mapped_column(JSONB, default=list)
    mastery_changes: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    interaction_style: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    sentiment: Mapped[str | None] = mapped_column(String(20), nullable=True)
    pending_items: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    model_used: Mapped[str | None] = mapped_column(String(50), nullable=True)
    session_duration_min: Mapped[int | None] = mapped_column(Integer, nullable=True)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
