"""Chinese (作文 + 古诗词) curriculum data — parsed from course-catalog.md

This module contains two complete courses for Chinese language:
  1. Composition (作文) — 1 course, 7 units, 23 lessons (incl. diagnostic)
  2. Poetry (古诗词赏析) — 1 course, 7 units, 25 lessons (incl. diagnostic)

Usage (by seed script):
    from scripts.curriculum_chinese import (
        CHINESE_COURSES, CHINESE_KNOWLEDGE_POINTS,
        CHINESE_KNOWLEDGE_DEPENDENCIES, CHINESE_PROBLEMS,
    )
"""

# ---------------------------------------------------------------------------
# Course 1: Composition (作文)
# ---------------------------------------------------------------------------

_COMP_COURSE = {
    "code": "CHN-COMP",
    "subject": "chn_composition",
    "name": "语文·作文课程",
    "description": "小学4-6年级作文训练，从记叙文到描写文到应用文，全面提升写作能力（字数目标300-500字）",
    "target_exam": None,
    "estimated_hours": 9,
    "is_published": True,
    "units": [
        # ------------------------------------------------------------------
        # Unit 0: Diagnostic
        # ------------------------------------------------------------------
        {
            "code": "CHN-COMP-U0",
            "name": "入学诊断",
            "description": "语文基础评估，包括阅读理解、片段写作、古诗词默写，生成知识画像",
            "sort_order": 0,
            "required_mastery": 0.0,
            "lessons": [
                {
                    "code": "DIAG-CHN",
                    "title": "语文入学诊断",
                    "lesson_type": "diagnostic",
                    "estimated_minutes": 25,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-DIAG",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "diagnostic",
                        "chn_grade": "4-6",
                        "objectives": ["语文基础评估", "生成知识画像", "确定起始模块"],
                        "knowledge_point_codes": ["CHN-DIAG"],
                        "prerequisite_codes": [],
                        "estimated_minutes": 25,
                        "xp_base": 0,
                        "steps": [],
                        "summary": {
                            "key_points": ["阅读理解", "片段写作", "古诗词默写"],
                            "common_mistakes": [],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 1: Module A — 写作基础
        # ------------------------------------------------------------------
        {
            "code": "CHN-COMP-U1",
            "name": "Module A 写作基础",
            "description": "学会观察、把句子写生动、段落的秘密、好开头与好结尾",
            "sort_order": 1,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-A1",
                    "title": "学会观察",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-A01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["用五官感受世界", "观察日记", "抓住特点"],
                        "knowledge_point_codes": ["CHN-COMP-A01"],
                        "prerequisite_codes": [],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["五官观察法", "观察日记", "抓住事物特点"],
                            "common_mistakes": ["观察不细致", "描述笼统"],
                        },
                    },
                },
                {
                    "code": "CHN-A2",
                    "title": "把句子写生动",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-A02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["比喻修辞入门", "拟人修辞入门", "排比修辞入门", "从平铺直叙到生动表达"],
                        "knowledge_point_codes": ["CHN-COMP-A02"],
                        "prerequisite_codes": ["CHN-A1"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["比喻、拟人、排比", "从平淡到生动"],
                            "common_mistakes": ["比喻不当", "拟人生硬"],
                        },
                    },
                },
                {
                    "code": "CHN-A3",
                    "title": "段落的秘密",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-A03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["总分总结构", "总分结构", "过渡句", "中心句"],
                        "knowledge_point_codes": ["CHN-COMP-A03"],
                        "prerequisite_codes": ["CHN-A2"],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["总分总结构", "总分结构", "过渡句与中心句"],
                            "common_mistakes": ["段落无中心", "缺少过渡"],
                        },
                    },
                },
                {
                    "code": "CHN-A4",
                    "title": "好开头与好结尾",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-A04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["开门见山开头", "设问开头", "引用开头", "呼应结尾", "感悟结尾"],
                        "knowledge_point_codes": ["CHN-COMP-A04"],
                        "prerequisite_codes": ["CHN-A3"],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["五种开头方法", "三种结尾技巧"],
                            "common_mistakes": ["开头啰嗦", "结尾仓促"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 2: Module B — 记叙文写作
        # ------------------------------------------------------------------
        {
            "code": "CHN-COMP-U2",
            "name": "Module B 记叙文写作",
            "description": "记事六要素、把事情写具体、写人的妙招、写一个精彩的故事、记叙文完整练习",
            "sort_order": 2,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-B1",
                    "title": "记事六要素",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-B01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["时间、地点、人物", "起因、经过、结果", "完整叙事"],
                        "knowledge_point_codes": ["CHN-COMP-B01"],
                        "prerequisite_codes": ["CHN-A4"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["记叙文六要素", "完整叙事结构"],
                            "common_mistakes": ["要素不全", "叙事不完整"],
                        },
                    },
                },
                {
                    "code": "CHN-B2",
                    "title": "把事情写具体",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-B02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["动作描写", "神态描写", "细节放大镜", "避免流水账"],
                        "knowledge_point_codes": ["CHN-COMP-B02"],
                        "prerequisite_codes": ["CHN-B1"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["动作描写细化", "神态描写", "避免流水账"],
                            "common_mistakes": ["只叙事不描写", "流水账式写作"],
                        },
                    },
                },
                {
                    "code": "CHN-B3",
                    "title": "写人的妙招",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-B03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["外貌描写", "语言描写", "心理活动", "通过事件表现人物"],
                        "knowledge_point_codes": ["CHN-COMP-B03"],
                        "prerequisite_codes": ["CHN-B1"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["外貌描写抓特征", "语言描写要真实", "心理描写要细腻"],
                            "common_mistakes": ["外貌描写面面俱到", "语言不符合人物身份"],
                        },
                    },
                },
                {
                    "code": "CHN-B4",
                    "title": "写一个精彩的故事",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-B04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["起承转合", "设置悬念", "制造波折", "结尾出人意料"],
                        "knowledge_point_codes": ["CHN-COMP-B04"],
                        "prerequisite_codes": ["CHN-B2", "CHN-B3"],
                        "estimated_minutes": 25,
                        "xp_base": 110,
                        "steps": [],
                        "summary": {
                            "key_points": ["起承转合结构", "悬念与波折"],
                            "common_mistakes": ["平铺直叙", "缺乏波折"],
                        },
                    },
                },
                {
                    "code": "CHN-B5",
                    "title": "记叙文完整练习",
                    "lesson_type": "composition",
                    "estimated_minutes": 35,
                    "sort_order": 5,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-B05",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "composition",
                        "chn_grade": "4-6",
                        "objectives": ["限时写作(300-400字)", "AI多维度评分"],
                        "knowledge_point_codes": ["CHN-COMP-B05"],
                        "prerequisite_codes": ["CHN-B4"],
                        "estimated_minutes": 35,
                        "xp_base": 150,
                        "steps": [],
                        "summary": {
                            "key_points": ["限时写作", "AI评分：内容/结构/语言/书写"],
                            "common_mistakes": ["时间不够", "字数不足"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 3: Module C — 描写文写作
        # ------------------------------------------------------------------
        {
            "code": "CHN-COMP-U3",
            "name": "Module C 描写文写作",
            "description": "写景的技巧、状物作文、描写文完整练习",
            "sort_order": 3,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-C1",
                    "title": "写景的技巧",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-C01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["按空间/时间顺序写景", "动静结合", "调动五官"],
                        "knowledge_point_codes": ["CHN-COMP-C01"],
                        "prerequisite_codes": ["CHN-A4"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["空间顺序", "时间顺序", "动静结合"],
                            "common_mistakes": ["写景无序", "只写静景"],
                        },
                    },
                },
                {
                    "code": "CHN-C2",
                    "title": "状物作文",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-C02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["写外形、特点、功能、感受", "托物言志"],
                        "knowledge_point_codes": ["CHN-COMP-C02"],
                        "prerequisite_codes": ["CHN-A4"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["状物顺序", "托物言志"],
                            "common_mistakes": ["只列数据无感受", "特征不突出"],
                        },
                    },
                },
                {
                    "code": "CHN-C3",
                    "title": "描写文完整练习",
                    "lesson_type": "composition",
                    "estimated_minutes": 30,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-C03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "composition",
                        "chn_grade": "4-6",
                        "objectives": ["限时写作", "AI评分"],
                        "knowledge_point_codes": ["CHN-COMP-C03"],
                        "prerequisite_codes": ["CHN-C1", "CHN-C2"],
                        "estimated_minutes": 30,
                        "xp_base": 130,
                        "steps": [],
                        "summary": {
                            "key_points": ["限时描写文写作", "AI多维度评分"],
                            "common_mistakes": ["描写不够具体", "缺乏感受"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 4: Module D — 想象作文
        # ------------------------------------------------------------------
        {
            "code": "CHN-COMP-U4",
            "name": "Module D 想象作文",
            "description": "看图写话进阶、假如我是…、童话与寓言创作",
            "sort_order": 4,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-D1",
                    "title": "看图写话进阶",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-D01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["从图片到故事", "观察→联想→构思→表达"],
                        "knowledge_point_codes": ["CHN-COMP-D01"],
                        "prerequisite_codes": ["CHN-B4"],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["四步法：观察→联想→构思→表达"],
                            "common_mistakes": ["只描述图片", "想象不合理"],
                        },
                    },
                },
                {
                    "code": "CHN-D2",
                    "title": "假如我是...",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-D02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["假想情境写作", "大胆想象", "合理表达"],
                        "knowledge_point_codes": ["CHN-COMP-D02"],
                        "prerequisite_codes": ["CHN-B4"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["假想情境设定", "想象与逻辑平衡"],
                            "common_mistakes": ["想象脱离现实", "缺乏逻辑"],
                        },
                    },
                },
                {
                    "code": "CHN-D3",
                    "title": "童话与寓言创作",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-D03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["角色设定", "情节设计", "寓意表达"],
                        "knowledge_point_codes": ["CHN-COMP-D03"],
                        "prerequisite_codes": ["CHN-D2"],
                        "estimated_minutes": 25,
                        "xp_base": 110,
                        "steps": [],
                        "summary": {
                            "key_points": ["角色设定技巧", "寓言寓意表达"],
                            "common_mistakes": ["缺乏寓意", "角色单一"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 5: Module E — 应用文写作
        # ------------------------------------------------------------------
        {
            "code": "CHN-COMP-U5",
            "name": "Module E 应用文写作",
            "description": "日记与读书笔记、书信与通知、演讲稿写作",
            "sort_order": 5,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-E1",
                    "title": "日记与读书笔记",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-E01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["日记格式", "读书笔记三要素(摘抄+感想+联想)"],
                        "knowledge_point_codes": ["CHN-COMP-E01"],
                        "prerequisite_codes": ["CHN-A4"],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["日记格式", "读书笔记三要素"],
                            "common_mistakes": ["日记写成流水账", "读书笔记只有摘抄"],
                        },
                    },
                },
                {
                    "code": "CHN-E2",
                    "title": "书信与通知",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-E02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["书信格式(称呼、正文、祝语、署名)", "通知格式"],
                        "knowledge_point_codes": ["CHN-COMP-E02"],
                        "prerequisite_codes": ["CHN-A4"],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["书信六部分", "通知格式"],
                            "common_mistakes": ["格式错误", "称呼和祝语不当"],
                        },
                    },
                },
                {
                    "code": "CHN-E3",
                    "title": "演讲稿写作",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-E03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["开场白", "论点论据", "号召结尾"],
                        "knowledge_point_codes": ["CHN-COMP-E03"],
                        "prerequisite_codes": ["CHN-E2"],
                        "estimated_minutes": 20,
                        "xp_base": 90,
                        "steps": [],
                        "summary": {
                            "key_points": ["开场白技巧", "论点论据结构", "号召式结尾"],
                            "common_mistakes": ["开场无吸引力", "论据不充分"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 6: Module F — 综合提升
        # ------------------------------------------------------------------
        {
            "code": "CHN-COMP-U6",
            "name": "Module F 综合提升",
            "description": "审题训练、语言润色、限时写作模拟、考试策略",
            "sort_order": 6,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-F1",
                    "title": "审题训练",
                    "lesson_type": "concept",
                    "estimated_minutes": 20,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-F01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["抓关键词", "判断文体", "确定中心"],
                        "knowledge_point_codes": ["CHN-COMP-F01"],
                        "prerequisite_codes": ["CHN-B5", "CHN-C3"],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["审题三步法", "抓关键词", "确定文体与中心"],
                            "common_mistakes": ["偏题", "文体判断错误"],
                        },
                    },
                },
                {
                    "code": "CHN-F2",
                    "title": "语言润色",
                    "lesson_type": "concept",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-F02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["好词好句运用", "句式变换", "删繁就简"],
                        "knowledge_point_codes": ["CHN-COMP-F02"],
                        "prerequisite_codes": ["CHN-B5"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["好词好句积累", "句式变换技巧", "删繁就简"],
                            "common_mistakes": ["堆砌辞藻", "句式单一"],
                        },
                    },
                },
                {
                    "code": "CHN-F3",
                    "title": "限时写作模拟",
                    "lesson_type": "composition",
                    "estimated_minutes": 40,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-F03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "composition",
                        "chn_grade": "4-6",
                        "objectives": ["30分钟完成一篇完整作文(400-500字)", "AI评分"],
                        "knowledge_point_codes": ["CHN-COMP-F03"],
                        "prerequisite_codes": ["CHN-F1", "CHN-F2"],
                        "estimated_minutes": 40,
                        "xp_base": 150,
                        "steps": [],
                        "summary": {
                            "key_points": ["限时写作", "完整作文", "AI评分"],
                            "common_mistakes": ["时间不够", "字数不足"],
                        },
                    },
                },
                {
                    "code": "CHN-F4",
                    "title": "考试策略",
                    "lesson_type": "concept",
                    "estimated_minutes": 15,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-COMP-F04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_composition",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["时间分配(审题5分+构思5分+写作20分)", "检查要点"],
                        "knowledge_point_codes": ["CHN-COMP-F04"],
                        "prerequisite_codes": ["CHN-F3"],
                        "estimated_minutes": 15,
                        "xp_base": 60,
                        "steps": [],
                        "summary": {
                            "key_points": ["时间分配", "检查要点"],
                            "common_mistakes": ["审题时间不足", "不检查"],
                        },
                    },
                },
            ],
        },
    ],
}

# ---------------------------------------------------------------------------
# Course 2: Poetry (古诗词赏析)
# ---------------------------------------------------------------------------

_POET_COURSE = {
    "code": "CHN-POETRY",
    "subject": "chn_poetry",
    "name": "语文·古诗词赏析课程",
    "description": "小学4-6年级古诗词赏析与背诵，覆盖课标必背古诗词75首中的核心篇目，培养鉴赏能力与审美情趣",
    "target_exam": None,
    "estimated_hours": 10,
    "is_published": True,
    "units": [
        # ------------------------------------------------------------------
        # Unit 0: Diagnostic
        # ------------------------------------------------------------------
        {
            "code": "CHN-POET-U0",
            "name": "入学诊断",
            "description": "古诗词基础评估",
            "sort_order": 0,
            "required_mastery": 0.0,
            "lessons": [
                {
                    "code": "DIAG-CHN-POETRY",
                    "title": "古诗词入学诊断",
                    "lesson_type": "diagnostic",
                    "estimated_minutes": 25,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-DIAG",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "diagnostic",
                        "chn_grade": "4-6",
                        "objectives": ["古诗词基础评估", "确定起始模块"],
                        "knowledge_point_codes": ["CHN-P-DIAG"],
                        "prerequisite_codes": [],
                        "estimated_minutes": 25,
                        "xp_base": 0,
                        "steps": [],
                        "summary": {
                            "key_points": ["古诗词基础", "默写能力", "鉴赏能力"],
                            "common_mistakes": [],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 1: Module A — 诗词入门
        # ------------------------------------------------------------------
        {
            "code": "CHN-POET-U1",
            "name": "Module A 诗词入门",
            "description": "古诗的节奏与韵律、认识诗人和朝代、常见意象解读、常见修辞手法",
            "sort_order": 1,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-PA1",
                    "title": "古诗的节奏与韵律",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 20,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-A01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["五言/七言节奏划分", "押韵", "朗读节奏标记"],
                        "knowledge_point_codes": ["CHN-P-A01"],
                        "prerequisite_codes": [],
                        "estimated_minutes": 20,
                        "xp_base": 70,
                        "steps": [],
                        "summary": {
                            "key_points": ["五言节奏：二二一", "七言节奏：二二二一", "押韵规则"],
                            "common_mistakes": ["节奏划分错误", "朗读无停顿"],
                        },
                    },
                },
                {
                    "code": "CHN-PA2",
                    "title": "认识诗人和朝代",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 20,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-A02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["唐宋主要诗人小传", "历史朝代顺序"],
                        "knowledge_point_codes": ["CHN-P-A02"],
                        "prerequisite_codes": ["CHN-PA1"],
                        "estimated_minutes": 20,
                        "xp_base": 70,
                        "steps": [],
                        "summary": {
                            "key_points": ["唐宋诗人", "朝代顺序", "诗人风格特点"],
                            "common_mistakes": ["朝代顺序混淆", "诗人与作品匹配错误"],
                        },
                    },
                },
                {
                    "code": "CHN-PA3",
                    "title": "常见意象解读",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-A03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["月亮(思乡)", "柳树(送别)", "梅花(坚韧)", "春风(生机)", "大雁(传书)"],
                        "knowledge_point_codes": ["CHN-P-A03"],
                        "prerequisite_codes": ["CHN-PA1"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["常见意象及含义", "意象与情感对应"],
                            "common_mistakes": ["意象含义混淆", "忽略语境"],
                        },
                    },
                },
                {
                    "code": "CHN-PA4",
                    "title": "常见修辞手法",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-A04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["比喻(明喻暗喻)", "拟人", "夸张", "对偶", "设问反问"],
                        "knowledge_point_codes": ["CHN-P-A04"],
                        "prerequisite_codes": ["CHN-PA2"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["五大修辞手法", "识别与赏析"],
                            "common_mistakes": ["比喻和拟人混淆", "忽略修辞效果"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 2: Module B — 四季诗篇
        # ------------------------------------------------------------------
        {
            "code": "CHN-POET-U2",
            "name": "Module B 四季诗篇",
            "description": "春之声、夏之韵、秋之思、冬之趣",
            "sort_order": 2,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-PB1",
                    "title": "春之声",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-B01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《春晓》孟浩然", "《绝句》杜甫", "《忆江南》白居易", "《村居》高鼎"],
                        "knowledge_point_codes": ["CHN-P-B01"],
                        "prerequisite_codes": ["CHN-PA4"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["春景诗特点", "惜春与爱春情感"],
                            "common_mistakes": ["忽略诗歌深层情感"],
                        },
                    },
                },
                {
                    "code": "CHN-PB2",
                    "title": "夏之韵",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 20,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-B02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《小池》杨万里", "《晓出净慈寺送林子方》杨万里", "《六月二十七日望湖楼醉书》苏轼"],
                        "knowledge_point_codes": ["CHN-P-B02"],
                        "prerequisite_codes": ["CHN-PB1"],
                        "estimated_minutes": 20,
                        "xp_base": 70,
                        "steps": [],
                        "summary": {
                            "key_points": ["夏景诗意象", "杨万里风格"],
                            "common_mistakes": ["不能区分不同诗人的写景手法"],
                        },
                    },
                },
                {
                    "code": "CHN-PB3",
                    "title": "秋之思",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-B03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《山行》杜牧", "《枫桥夜泊》张继", "《秋思》张籍", "《天净沙·秋》白朴"],
                        "knowledge_point_codes": ["CHN-P-B03"],
                        "prerequisite_codes": ["CHN-PB1"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["秋景与思乡", "悲秋与赏秋"],
                            "common_mistakes": ["混淆不同秋诗情感"],
                        },
                    },
                },
                {
                    "code": "CHN-PB4",
                    "title": "冬之趣",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 20,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-B04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《江雪》柳宗元", "《梅花》王安石", "《白雪歌送武判官归京》岑参(节选)"],
                        "knowledge_point_codes": ["CHN-P-B04"],
                        "prerequisite_codes": ["CHN-PB3"],
                        "estimated_minutes": 20,
                        "xp_base": 70,
                        "steps": [],
                        "summary": {
                            "key_points": ["冬景意象", "咏梅与咏雪"],
                            "common_mistakes": ["忽略咏物诗的象征意义"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 3: Module C — 山水田园
        # ------------------------------------------------------------------
        {
            "code": "CHN-POET-U3",
            "name": "Module C 山水田园",
            "description": "壮美山河、田园牧歌、闲情雅趣",
            "sort_order": 3,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-PC1",
                    "title": "壮美山河",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-C01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《望庐山瀑布》李白", "《望天门山》李白", "《题西林壁》苏轼", "《饮湖上初晴后雨》苏轼"],
                        "knowledge_point_codes": ["CHN-P-C01"],
                        "prerequisite_codes": ["CHN-PB1"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["山水诗特点", "夸张与想象手法"],
                            "common_mistakes": ["忽略诗歌的想象成分"],
                        },
                    },
                },
                {
                    "code": "CHN-PC2",
                    "title": "田园牧歌",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-C02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《田园四时杂兴》范成大", "《乡村四月》翁卷", "《四时田园杂兴》范成大"],
                        "knowledge_point_codes": ["CHN-P-C02"],
                        "prerequisite_codes": ["CHN-PC1"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["田园诗特点", "范成大风格"],
                            "common_mistakes": ["不能区分田园诗和山水诗"],
                        },
                    },
                },
                {
                    "code": "CHN-PC3",
                    "title": "闲情雅趣",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 20,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-C03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《竹里馆》王维", "《独坐敬亭山》李白", "《渔歌子》张志和", "《游园不值》叶绍翁"],
                        "knowledge_point_codes": ["CHN-P-C03"],
                        "prerequisite_codes": ["CHN-PC1"],
                        "estimated_minutes": 20,
                        "xp_base": 70,
                        "steps": [],
                        "summary": {
                            "key_points": ["闲适诗特点", "诗中有画"],
                            "common_mistakes": ["忽略诗歌的情感层次"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 4: Module D — 情感世界
        # ------------------------------------------------------------------
        {
            "code": "CHN-POET-U4",
            "name": "Module D 情感世界",
            "description": "思乡之情、送别之情、爱国情怀、咏物言志",
            "sort_order": 4,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-PD1",
                    "title": "思乡之情",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-D01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《静夜思》李白", "《九月九日忆山东兄弟》王维", "《泊船瓜洲》王安石", "《秋思》张籍"],
                        "knowledge_point_codes": ["CHN-P-D01"],
                        "prerequisite_codes": ["CHN-PC1"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["思乡意象：月亮、秋风", "借景抒情手法"],
                            "common_mistakes": ["不能准确概括诗人情感"],
                        },
                    },
                },
                {
                    "code": "CHN-PD2",
                    "title": "送别之情",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-D02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《送元二使安西》王维", "《黄鹤楼送孟浩然之广陵》李白", "《赠汪伦》李白", "《别董大》高适"],
                        "knowledge_point_codes": ["CHN-P-D02"],
                        "prerequisite_codes": ["CHN-PD1"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["送别意象：柳、酒、长亭", "送别诗的常见情感"],
                            "common_mistakes": ["混淆不同送别诗的情感基调"],
                        },
                    },
                },
                {
                    "code": "CHN-PD3",
                    "title": "爱国情怀",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-D03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《出塞》王昌龄", "《示儿》陆游", "《题临安邸》林升", "《夏日绝句》李清照"],
                        "knowledge_point_codes": ["CHN-P-D03"],
                        "prerequisite_codes": ["CHN-PD1"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["爱国诗特点", "家国情怀表达"],
                            "common_mistakes": ["忽略历史背景"],
                        },
                    },
                },
                {
                    "code": "CHN-PD4",
                    "title": "咏物言志",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-D04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["《石灰吟》于谦", "《竹石》郑燮", "《墨梅》王冕", "《蜂》罗隐"],
                        "knowledge_point_codes": ["CHN-P-D04"],
                        "prerequisite_codes": ["CHN-PD3"],
                        "estimated_minutes": 25,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["咏物诗特点", "托物言志手法"],
                            "common_mistakes": ["只描写物不理解志"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 5: Module E — 名家名篇
        # ------------------------------------------------------------------
        {
            "code": "CHN-POET-U5",
            "name": "Module E 名家名篇",
            "description": "李白、杜甫、王维、苏轼与宋词",
            "sort_order": 5,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-PE1",
                    "title": "李白 — 诗仙",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 30,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-E01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["浪漫主义风格", "想象奇特", "豪放不羁", "精读3-4首代表作"],
                        "knowledge_point_codes": ["CHN-P-E01"],
                        "prerequisite_codes": ["CHN-PD4"],
                        "estimated_minutes": 30,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["李白风格特点", "浪漫主义", "代表作品赏析"],
                            "common_mistakes": ["不能概括李白风格"],
                        },
                    },
                },
                {
                    "code": "CHN-PE2",
                    "title": "杜甫 — 诗圣",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 30,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-E02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["现实主义风格", "忧国忧民", "沉郁顿挫", "精读3-4首代表作"],
                        "knowledge_point_codes": ["CHN-P-E02"],
                        "prerequisite_codes": ["CHN-PE1"],
                        "estimated_minutes": 30,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["杜甫风格特点", "现实主义", "与李白对比"],
                            "common_mistakes": ["混淆浪漫主义和现实主义"],
                        },
                    },
                },
                {
                    "code": "CHN-PE3",
                    "title": "王维 — 诗中有画",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-E03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["山水田园", "禅意诗境", "诗画一体", "精读3-4首代表作"],
                        "knowledge_point_codes": ["CHN-P-E03"],
                        "prerequisite_codes": ["CHN-PE2"],
                        "estimated_minutes": 25,
                        "xp_base": 90,
                        "steps": [],
                        "summary": {
                            "key_points": ["王维风格特点", "诗中有画", "禅意"],
                            "common_mistakes": ["忽略禅意层面"],
                        },
                    },
                },
                {
                    "code": "CHN-PE4",
                    "title": "苏轼与宋词",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-E04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["豪放词风", "《水调歌头》《题西林壁》", "宋词入门"],
                        "knowledge_point_codes": ["CHN-P-E04"],
                        "prerequisite_codes": ["CHN-PE3"],
                        "estimated_minutes": 25,
                        "xp_base": 90,
                        "steps": [],
                        "summary": {
                            "key_points": ["苏轼风格", "宋词与唐诗区别", "豪放词"],
                            "common_mistakes": ["混淆诗和词的格式"],
                        },
                    },
                },
            ],
        },
        # ------------------------------------------------------------------
        # Unit 6: Module F — 综合训练
        # ------------------------------------------------------------------
        {
            "code": "CHN-POET-U6",
            "name": "Module F 综合训练",
            "description": "诗词默写检测、理解性默写、鉴赏题型训练、综合模拟测试、考试策略",
            "sort_order": 6,
            "required_mastery": 0.8,
            "lessons": [
                {
                    "code": "CHN-PF1",
                    "title": "诗词默写检测",
                    "lesson_type": "poetry_dictation",
                    "estimated_minutes": 20,
                    "sort_order": 1,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-F01",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_dictation",
                        "chn_grade": "4-6",
                        "objectives": ["间隔重复系统抽测", "准确默写"],
                        "knowledge_point_codes": ["CHN-P-F01"],
                        "prerequisite_codes": ["CHN-PE4"],
                        "estimated_minutes": 20,
                        "xp_base": 80,
                        "steps": [],
                        "summary": {
                            "key_points": ["准确默写", "易错字辨析"],
                            "common_mistakes": ["同音字错误", "形近字混淆"],
                        },
                    },
                },
                {
                    "code": "CHN-PF2",
                    "title": "理解性默写",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 2,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-F02",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["情境填空", "主题归类", "意象对应"],
                        "knowledge_point_codes": ["CHN-P-F02"],
                        "prerequisite_codes": ["CHN-PF1"],
                        "estimated_minutes": 25,
                        "xp_base": 90,
                        "steps": [],
                        "summary": {
                            "key_points": ["情境默写", "主题归类默写", "意象对应"],
                            "common_mistakes": ["不理解题意就默写", "张冠李戴"],
                        },
                    },
                },
                {
                    "code": "CHN-PF3",
                    "title": "鉴赏题型训练",
                    "lesson_type": "poetry_reading",
                    "estimated_minutes": 25,
                    "sort_order": 3,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-F03",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "poetry_reading",
                        "chn_grade": "4-6",
                        "objectives": ["分析表现手法", "理解情感", "品味语言"],
                        "knowledge_point_codes": ["CHN-P-F03"],
                        "prerequisite_codes": ["CHN-PF2"],
                        "estimated_minutes": 25,
                        "xp_base": 100,
                        "steps": [],
                        "summary": {
                            "key_points": ["四步答题法", "表现手法分析", "情感概括"],
                            "common_mistakes": ["答题不完整", "手法分析笼统"],
                        },
                    },
                },
                {
                    "code": "CHN-PF4",
                    "title": "综合模拟测试",
                    "lesson_type": "assessment",
                    "estimated_minutes": 30,
                    "sort_order": 4,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-F04",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "assessment",
                        "chn_grade": "4-6",
                        "objectives": ["默写+理解+鉴赏综合测试"],
                        "knowledge_point_codes": ["CHN-P-F04"],
                        "prerequisite_codes": ["CHN-PF3"],
                        "estimated_minutes": 30,
                        "xp_base": 120,
                        "steps": [],
                        "summary": {
                            "key_points": ["综合测试", "默写+理解+鉴赏"],
                            "common_mistakes": ["时间分配不当", "默写失分多"],
                        },
                    },
                },
                {
                    "code": "CHN-PF5",
                    "title": "考试策略",
                    "lesson_type": "concept",
                    "estimated_minutes": 15,
                    "sort_order": 5,
                    "is_published": True,
                    "knowledge_point_code": "CHN-P-F05",
                    "content": {
                        "schema_version": "1.0",
                        "subject": "chn_poetry",
                        "lesson_type": "concept",
                        "chn_grade": "4-6",
                        "objectives": ["答题技巧", "易错字提示", "时间管理"],
                        "knowledge_point_codes": ["CHN-P-F05"],
                        "prerequisite_codes": ["CHN-PF4"],
                        "estimated_minutes": 15,
                        "xp_base": 60,
                        "steps": [],
                        "summary": {
                            "key_points": ["答题技巧", "易错字", "时间管理"],
                            "common_mistakes": ["不留时间检查", "审题不仔细"],
                        },
                    },
                },
            ],
        },
    ],
}

CHINESE_COURSES = [_COMP_COURSE, _POET_COURSE]

# ---------------------------------------------------------------------------
# Knowledge Points
# ---------------------------------------------------------------------------

CHINESE_KNOWLEDGE_POINTS = [
    # === Composition ===
    {"code": "CHN-DIAG", "subject": "chn_composition", "name": "语文入学诊断", "name_en": "Chinese Placement Test",
     "description": "语文基础评估，包括阅读理解、片段写作、古诗词默写", "pillar": "diagnostic", "difficulty_level": 1, "amc_level": 0, "sort_order": 0, "estimated_minutes": 25},

    # Module A: Writing Basics
    {"code": "CHN-COMP-A01", "subject": "chn_composition", "name": "学会观察", "name_en": "Learning to Observe",
     "description": "用五官感受世界，观察日记，抓住特点", "pillar": "technique", "difficulty_level": 1, "amc_level": 0, "sort_order": 1, "estimated_minutes": 20},
    {"code": "CHN-COMP-A02", "subject": "chn_composition", "name": "把句子写生动", "name_en": "Writing Vivid Sentences",
     "description": "比喻、拟人、排比等修辞入门，从平铺直叙到生动表达", "pillar": "technique", "difficulty_level": 1, "amc_level": 0, "sort_order": 2, "estimated_minutes": 25},
    {"code": "CHN-COMP-A03", "subject": "chn_composition", "name": "段落的秘密", "name_en": "Secrets of Paragraphs",
     "description": "总分总结构、总分结构、过渡句、中心句", "pillar": "technique", "difficulty_level": 2, "amc_level": 0, "sort_order": 3, "estimated_minutes": 20},
    {"code": "CHN-COMP-A04", "subject": "chn_composition", "name": "好开头与好结尾", "name_en": "Great Openings and Endings",
     "description": "开门见山、设问开头、引用开头，呼应结尾、感悟结尾", "pillar": "technique", "difficulty_level": 2, "amc_level": 0, "sort_order": 4, "estimated_minutes": 20},

    # Module B: Narrative Writing
    {"code": "CHN-COMP-B01", "subject": "chn_composition", "name": "记事六要素", "name_en": "Six Elements of Narrative",
     "description": "时间、地点、人物、起因、经过、结果，完整叙事", "pillar": "composition", "difficulty_level": 2, "amc_level": 0, "sort_order": 5, "estimated_minutes": 25},
    {"code": "CHN-COMP-B02", "subject": "chn_composition", "name": "把事情写具体", "name_en": "Writing Specifics",
     "description": "动作描写、神态描写、细节放大镜，避免流水账", "pillar": "composition", "difficulty_level": 2, "amc_level": 0, "sort_order": 6, "estimated_minutes": 25},
    {"code": "CHN-COMP-B03", "subject": "chn_composition", "name": "写人的妙招", "name_en": "Tips for Character Writing",
     "description": "外貌描写、语言描写、心理活动，通过事件表现人物", "pillar": "composition", "difficulty_level": 2, "amc_level": 0, "sort_order": 7, "estimated_minutes": 25},
    {"code": "CHN-COMP-B04", "subject": "chn_composition", "name": "写一个精彩的故事", "name_en": "Writing an Exciting Story",
     "description": "起承转合、设置悬念、制造波折、结尾出人意料", "pillar": "composition", "difficulty_level": 3, "amc_level": 0, "sort_order": 8, "estimated_minutes": 25},
    {"code": "CHN-COMP-B05", "subject": "chn_composition", "name": "记叙文完整练习", "name_en": "Narrative Writing Practice",
     "description": "限时写作(300-400字) + AI多维度评分", "pillar": "composition", "difficulty_level": 3, "amc_level": 0, "sort_order": 9, "estimated_minutes": 35},

    # Module C: Descriptive Writing
    {"code": "CHN-COMP-C01", "subject": "chn_composition", "name": "写景的技巧", "name_en": "Landscape Writing Skills",
     "description": "按空间/时间顺序写景，动静结合，调动五官", "pillar": "composition", "difficulty_level": 2, "amc_level": 0, "sort_order": 10, "estimated_minutes": 25},
    {"code": "CHN-COMP-C02", "subject": "chn_composition", "name": "状物作文", "name_en": "Object Description Writing",
     "description": "写一样东西：外形、特点、功能、感受，托物言志", "pillar": "composition", "difficulty_level": 2, "amc_level": 0, "sort_order": 11, "estimated_minutes": 25},
    {"code": "CHN-COMP-C03", "subject": "chn_composition", "name": "描写文完整练习", "name_en": "Descriptive Writing Practice",
     "description": "限时写作 + AI评分", "pillar": "composition", "difficulty_level": 3, "amc_level": 0, "sort_order": 12, "estimated_minutes": 30},

    # Module D: Imaginative Writing
    {"code": "CHN-COMP-D01", "subject": "chn_composition", "name": "看图写话进阶", "name_en": "Advanced Picture Writing",
     "description": "从图片到故事：观察→联想→构思→表达", "pillar": "composition", "difficulty_level": 2, "amc_level": 0, "sort_order": 13, "estimated_minutes": 20},
    {"code": "CHN-COMP-D02", "subject": "chn_composition", "name": "假如我是...", "name_en": "If I Were...",
     "description": "假想情境写作，大胆想象，合理表达", "pillar": "composition", "difficulty_level": 2, "amc_level": 0, "sort_order": 14, "estimated_minutes": 25},
    {"code": "CHN-COMP-D03", "subject": "chn_composition", "name": "童话与寓言创作", "name_en": "Fairy Tales and Fables",
     "description": "角色设定、情节设计、寓意表达", "pillar": "composition", "difficulty_level": 3, "amc_level": 0, "sort_order": 15, "estimated_minutes": 25},

    # Module E: Practical Writing
    {"code": "CHN-COMP-E01", "subject": "chn_composition", "name": "日记与读书笔记", "name_en": "Diary and Reading Notes",
     "description": "日记格式、读书笔记三要素(摘抄+感想+联想)", "pillar": "practical", "difficulty_level": 1, "amc_level": 0, "sort_order": 16, "estimated_minutes": 20},
    {"code": "CHN-COMP-E02", "subject": "chn_composition", "name": "书信与通知", "name_en": "Letters and Notices",
     "description": "书信格式(称呼、正文、祝语、署名)、通知格式", "pillar": "practical", "difficulty_level": 2, "amc_level": 0, "sort_order": 17, "estimated_minutes": 20},
    {"code": "CHN-COMP-E03", "subject": "chn_composition", "name": "演讲稿写作", "name_en": "Speech Writing",
     "description": "开场白、论点论据、号召结尾", "pillar": "practical", "difficulty_level": 2, "amc_level": 0, "sort_order": 18, "estimated_minutes": 20},

    # Module F: Comprehensive
    {"code": "CHN-COMP-F01", "subject": "chn_composition", "name": "审题训练", "name_en": "Topic Analysis Training",
     "description": "抓关键词、判断文体、确定中心", "pillar": "technique", "difficulty_level": 2, "amc_level": 0, "sort_order": 19, "estimated_minutes": 20},
    {"code": "CHN-COMP-F02", "subject": "chn_composition", "name": "语言润色", "name_en": "Language Polishing",
     "description": "好词好句运用、句式变换、删繁就简", "pillar": "technique", "difficulty_level": 3, "amc_level": 0, "sort_order": 20, "estimated_minutes": 25},
    {"code": "CHN-COMP-F03", "subject": "chn_composition", "name": "限时写作模拟", "name_en": "Timed Writing Simulation",
     "description": "30分钟完成一篇完整作文(400-500字)", "pillar": "composition", "difficulty_level": 3, "amc_level": 0, "sort_order": 21, "estimated_minutes": 40},
    {"code": "CHN-COMP-F04", "subject": "chn_composition", "name": "考试策略", "name_en": "Exam Strategies",
     "description": "时间分配(审题5分+构思5分+写作20分)、检查要点", "pillar": "technique", "difficulty_level": 2, "amc_level": 0, "sort_order": 22, "estimated_minutes": 15},

    # === Poetry ===
    {"code": "CHN-P-DIAG", "subject": "chn_poetry", "name": "古诗词入学诊断", "name_en": "Poetry Placement Test",
     "description": "古诗词基础评估", "pillar": "diagnostic", "difficulty_level": 1, "amc_level": 0, "sort_order": 50, "estimated_minutes": 25},

    # Module A: Poetry Basics
    {"code": "CHN-P-A01", "subject": "chn_poetry", "name": "古诗的节奏与韵律", "name_en": "Rhythm and Rhyme in Classical Poetry",
     "description": "五言/七言节奏划分、押韵、朗读节奏标记", "pillar": "poetry", "difficulty_level": 1, "amc_level": 0, "sort_order": 51, "estimated_minutes": 20},
    {"code": "CHN-P-A02", "subject": "chn_poetry", "name": "认识诗人和朝代", "name_en": "Poets and Dynasties",
     "description": "唐宋主要诗人小传、历史朝代顺序", "pillar": "poetry", "difficulty_level": 1, "amc_level": 0, "sort_order": 52, "estimated_minutes": 20},
    {"code": "CHN-P-A03", "subject": "chn_poetry", "name": "常见意象解读", "name_en": "Common Imagery Interpretation",
     "description": "月亮(思乡)、柳树(送别)、梅花(坚韧)、春风(生机)、大雁(传书)", "pillar": "imagery", "difficulty_level": 2, "amc_level": 0, "sort_order": 53, "estimated_minutes": 25},
    {"code": "CHN-P-A04", "subject": "chn_poetry", "name": "常见修辞手法", "name_en": "Common Rhetorical Devices",
     "description": "比喻(明喻暗喻)、拟人、夸张、对偶、设问反问", "pillar": "rhetoric", "difficulty_level": 2, "amc_level": 0, "sort_order": 54, "estimated_minutes": 25},

    # Module B: Four Seasons
    {"code": "CHN-P-B01", "subject": "chn_poetry", "name": "春之声", "name_en": "Voices of Spring",
     "description": "《春晓》孟浩然、《绝句》杜甫、《忆江南》白居易、《村居》高鼎", "pillar": "poetry", "difficulty_level": 1, "amc_level": 0, "sort_order": 55, "estimated_minutes": 25},
    {"code": "CHN-P-B02", "subject": "chn_poetry", "name": "夏之韵", "name_en": "Rhythm of Summer",
     "description": "《小池》杨万里、《晓出净慈寺送林子方》杨万里、《六月二十七日望湖楼醉书》苏轼", "pillar": "poetry", "difficulty_level": 1, "amc_level": 0, "sort_order": 56, "estimated_minutes": 20},
    {"code": "CHN-P-B03", "subject": "chn_poetry", "name": "秋之思", "name_en": "Thoughts of Autumn",
     "description": "《山行》杜牧、《枫桥夜泊》张继、《秋思》张籍、《天净沙·秋》白朴", "pillar": "poetry", "difficulty_level": 2, "amc_level": 0, "sort_order": 57, "estimated_minutes": 25},
    {"code": "CHN-P-B04", "subject": "chn_poetry", "name": "冬之趣", "name_en": "Joy of Winter",
     "description": "《江雪》柳宗元、《梅花》王安石、《白雪歌送武判官归京》岑参(节选)", "pillar": "poetry", "difficulty_level": 2, "amc_level": 0, "sort_order": 58, "estimated_minutes": 20},

    # Module C: Mountains and Rivers
    {"code": "CHN-P-C01", "subject": "chn_poetry", "name": "壮美山河", "name_en": "Magnificent Landscapes",
     "description": "《望庐山瀑布》李白、《望天门山》李白、《题西林壁》苏轼、《饮湖上初晴后雨》苏轼", "pillar": "imagery", "difficulty_level": 2, "amc_level": 0, "sort_order": 59, "estimated_minutes": 25},
    {"code": "CHN-P-C02", "subject": "chn_poetry", "name": "田园牧歌", "name_en": "Pastoral Songs",
     "description": "《田园四时杂兴》范成大、《乡村四月》翁卷、《四时田园杂兴》范成大", "pillar": "imagery", "difficulty_level": 2, "amc_level": 0, "sort_order": 60, "estimated_minutes": 25},
    {"code": "CHN-P-C03", "subject": "chn_poetry", "name": "闲情雅趣", "name_en": "Leisure and Elegance",
     "description": "《竹里馆》王维、《独坐敬亭山》李白、《渔歌子》张志和、《游园不值》叶绍翁", "pillar": "imagery", "difficulty_level": 2, "amc_level": 0, "sort_order": 61, "estimated_minutes": 20},

    # Module D: Emotions
    {"code": "CHN-P-D01", "subject": "chn_poetry", "name": "思乡之情", "name_en": "Homesickness",
     "description": "《静夜思》李白、《九月九日忆山东兄弟》王维、《泊船瓜洲》王安石、《秋思》张籍", "pillar": "poetry", "difficulty_level": 2, "amc_level": 0, "sort_order": 62, "estimated_minutes": 25},
    {"code": "CHN-P-D02", "subject": "chn_poetry", "name": "送别之情", "name_en": "Farewell Feelings",
     "description": "《送元二使安西》王维、《黄鹤楼送孟浩然之广陵》李白、《赠汪伦》李白、《别董大》高适", "pillar": "poetry", "difficulty_level": 2, "amc_level": 0, "sort_order": 63, "estimated_minutes": 25},
    {"code": "CHN-P-D03", "subject": "chn_poetry", "name": "爱国情怀", "name_en": "Patriotism",
     "description": "《出塞》王昌龄、《示儿》陆游、《题临安邸》林升、《夏日绝句》李清照", "pillar": "poetry", "difficulty_level": 2, "amc_level": 0, "sort_order": 64, "estimated_minutes": 25},
    {"code": "CHN-P-D04", "subject": "chn_poetry", "name": "咏物言志", "name_en": "Object Poetry and Ambition",
     "description": "《石灰吟》于谦、《竹石》郑燮、《墨梅》王冕、《蜂》罗隐", "pillar": "rhetoric", "difficulty_level": 2, "amc_level": 0, "sort_order": 65, "estimated_minutes": 25},

    # Module E: Famous Poets
    {"code": "CHN-P-E01", "subject": "chn_poetry", "name": "李白 — 诗仙", "name_en": "Li Bai — The Immortal Poet",
     "description": "浪漫主义风格、想象奇特、豪放不羁", "pillar": "poetry", "difficulty_level": 3, "amc_level": 0, "sort_order": 66, "estimated_minutes": 30},
    {"code": "CHN-P-E02", "subject": "chn_poetry", "name": "杜甫 — 诗圣", "name_en": "Du Fu — The Sage Poet",
     "description": "现实主义风格、忧国忧民、沉郁顿挫", "pillar": "poetry", "difficulty_level": 3, "amc_level": 0, "sort_order": 67, "estimated_minutes": 30},
    {"code": "CHN-P-E03", "subject": "chn_poetry", "name": "王维 — 诗中有画", "name_en": "Wang Wei — Poetry in Painting",
     "description": "山水田园、禅意诗境、诗画一体", "pillar": "imagery", "difficulty_level": 3, "amc_level": 0, "sort_order": 68, "estimated_minutes": 25},
    {"code": "CHN-P-E04", "subject": "chn_poetry", "name": "苏轼与宋词", "name_en": "Su Shi and Song Ci",
     "description": "豪放词风、《水调歌头》《题西林壁》，宋词入门", "pillar": "poetry", "difficulty_level": 3, "amc_level": 0, "sort_order": 69, "estimated_minutes": 25},

    # Module F: Comprehensive Training
    {"code": "CHN-P-F01", "subject": "chn_poetry", "name": "诗词默写检测", "name_en": "Poetry Dictation Test",
     "description": "间隔重复系统抽测，准确默写", "pillar": "recitation", "difficulty_level": 2, "amc_level": 0, "sort_order": 70, "estimated_minutes": 20},
    {"code": "CHN-P-F02", "subject": "chn_poetry", "name": "理解性默写", "name_en": "Comprehension Dictation",
     "description": "常考题型：情境填空、主题归类、意象对应", "pillar": "recitation", "difficulty_level": 2, "amc_level": 0, "sort_order": 71, "estimated_minutes": 25},
    {"code": "CHN-P-F03", "subject": "chn_poetry", "name": "鉴赏题型训练", "name_en": "Appreciation Question Training",
     "description": "分析表现手法、理解情感、品味语言", "pillar": "rhetoric", "difficulty_level": 3, "amc_level": 0, "sort_order": 72, "estimated_minutes": 25},
    {"code": "CHN-P-F04", "subject": "chn_poetry", "name": "综合模拟测试", "name_en": "Comprehensive Mock Test",
     "description": "默写+理解+鉴赏综合测试", "pillar": "poetry", "difficulty_level": 3, "amc_level": 0, "sort_order": 73, "estimated_minutes": 30},
    {"code": "CHN-P-F05", "subject": "chn_poetry", "name": "考试策略", "name_en": "Exam Strategies",
     "description": "答题技巧、易错字提示、时间管理", "pillar": "poetry", "difficulty_level": 2, "amc_level": 0, "sort_order": 74, "estimated_minutes": 15},
]

# ---------------------------------------------------------------------------
# Knowledge Dependencies
# ---------------------------------------------------------------------------

CHINESE_KNOWLEDGE_DEPENDENCIES = [
    # === Composition ===
    # Module A chain
    ("CHN-COMP-A01", "CHN-COMP-A02", "requires", 1),
    ("CHN-COMP-A02", "CHN-COMP-A03", "requires", 1),
    ("CHN-COMP-A03", "CHN-COMP-A04", "requires", 1),

    # Module B
    ("CHN-COMP-A04", "CHN-COMP-B01", "requires", 1),
    ("CHN-COMP-B01", "CHN-COMP-B02", "requires", 1),
    ("CHN-COMP-B01", "CHN-COMP-B03", "requires", 1),
    ("CHN-COMP-B02", "CHN-COMP-B04", "requires", 1),
    ("CHN-COMP-B03", "CHN-COMP-B04", "requires", 1),
    ("CHN-COMP-B04", "CHN-COMP-B05", "requires", 1),

    # Module C
    ("CHN-COMP-A04", "CHN-COMP-C01", "requires", 1),
    ("CHN-COMP-A04", "CHN-COMP-C02", "requires", 1),
    ("CHN-COMP-C01", "CHN-COMP-C03", "requires", 1),
    ("CHN-COMP-C02", "CHN-COMP-C03", "requires", 1),

    # Module D
    ("CHN-COMP-B04", "CHN-COMP-D01", "requires", 1),
    ("CHN-COMP-B04", "CHN-COMP-D02", "requires", 1),
    ("CHN-COMP-D02", "CHN-COMP-D03", "requires", 1),

    # Module E
    ("CHN-COMP-A04", "CHN-COMP-E01", "requires", 1),
    ("CHN-COMP-A04", "CHN-COMP-E02", "requires", 1),
    ("CHN-COMP-E02", "CHN-COMP-E03", "requires", 1),

    # Module F
    ("CHN-COMP-B05", "CHN-COMP-F01", "requires", 1),
    ("CHN-COMP-C03", "CHN-COMP-F01", "requires", 1),
    ("CHN-COMP-B05", "CHN-COMP-F02", "requires", 1),
    ("CHN-COMP-F01", "CHN-COMP-F03", "requires", 1),
    ("CHN-COMP-F02", "CHN-COMP-F03", "requires", 1),
    ("CHN-COMP-F03", "CHN-COMP-F04", "requires", 1),

    # === Poetry ===
    # Module A chain
    ("CHN-P-A01", "CHN-P-A02", "requires", 1),
    ("CHN-P-A01", "CHN-P-A03", "requires", 1),
    ("CHN-P-A02", "CHN-P-A04", "requires", 1),

    # Module B: Four Seasons
    ("CHN-P-A04", "CHN-P-B01", "requires", 1),
    ("CHN-P-B01", "CHN-P-B02", "requires", 1),
    ("CHN-P-B01", "CHN-P-B03", "requires", 1),
    ("CHN-P-B03", "CHN-P-B04", "requires", 1),

    # Module C: Mountains and Rivers
    ("CHN-P-B01", "CHN-P-C01", "requires", 1),
    ("CHN-P-C01", "CHN-P-C02", "requires", 1),
    ("CHN-P-C01", "CHN-P-C03", "requires", 1),

    # Module D: Emotions
    ("CHN-P-C01", "CHN-P-D01", "requires", 1),
    ("CHN-P-D01", "CHN-P-D02", "requires", 1),
    ("CHN-P-D01", "CHN-P-D03", "requires", 1),
    ("CHN-P-D03", "CHN-P-D04", "requires", 1),

    # Module E: Famous Poets
    ("CHN-P-D04", "CHN-P-E01", "requires", 1),
    ("CHN-P-E01", "CHN-P-E02", "requires", 1),
    ("CHN-P-E02", "CHN-P-E03", "requires", 1),
    ("CHN-P-E03", "CHN-P-E04", "requires", 1),

    # Module F: Comprehensive Training
    ("CHN-P-E04", "CHN-P-F01", "requires", 1),
    ("CHN-P-F01", "CHN-P-F02", "requires", 1),
    ("CHN-P-F02", "CHN-P-F03", "requires", 1),
    ("CHN-P-F03", "CHN-P-F04", "requires", 1),
    ("CHN-P-F04", "CHN-P-F05", "requires", 1),
]

# ---------------------------------------------------------------------------
# Problems
# ---------------------------------------------------------------------------

CHINESE_PROBLEMS = [
    # === Composition: Module A ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-A1-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n以下哪种不是「五官观察法」中的观察方式？",
        "options": {"A": "用眼睛看", "B": "用耳朵听", "C": "用手摸", "D": "用尺量"},
        "correct_answer": "D", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-A01"],
        "hints": ["五官是：视觉、听觉、嗅觉、味觉、触觉。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-A2-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n「春天来了，花儿露出了笑脸」使用了什么修辞手法？",
        "options": {"A": "比喻", "B": "拟人", "C": "排比", "D": "夸张"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-A02"],
        "hints": ["'笑脸'是人的特征，赋予花儿就是拟人。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-A3-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n「春天来了，万物复苏。小草绿了，花儿开了，燕子飞回来了。大自然真是一幅美丽的画卷！」这段话的结构是？",
        "options": {"A": "总分总", "B": "总分", "C": "分总", "D": "并列"},
        "correct_answer": "A", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-A03"],
        "hints": ["先总述（春天来了），再分述（小草、花儿、燕子），最后总结。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-A4-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n以下哪种不是好的作文开头方式？",
        "options": {"A": "开门见山", "B": "设问开头", "C": "引用名言", "D": "从天气写起（与主题无关）"},
        "correct_answer": "D", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-A04"],
        "hints": ["好的开头要与主题相关。"],
    },

    # === Composition: Module B ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-B1-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n记叙文的六要素不包括以下哪一项？",
        "options": {"A": "时间", "B": "地点", "C": "人物", "D": "论点"},
        "correct_answer": "D", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-B01"],
        "hints": ["六要素是：时间、地点、人物、起因、经过、结果。论点是议论文的要素。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-B2-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n「他一溜烟跑到了操场」中，哪个词语属于动作描写？",
        "options": {"A": "他", "B": "一溜烟", "C": "跑", "D": "操场"},
        "correct_answer": "C", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-B02"],
        "hints": ["'跑'是一个具体的动作。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-B3-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n「他的脸红得像苹果」用了什么描写方法？",
        "options": {"A": "动作描写", "B": "语言描写", "C": "外貌描写", "D": "心理描写"},
        "correct_answer": "C", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-B03"],
        "hints": ["描写脸的外在样子属于外貌描写。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-B4-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n「起承转合」中，「转」的意思是？",
        "options": {"A": "开始叙述", "B": "继续发展", "C": "转折变化", "D": "总结结尾"},
        "correct_answer": "C", "difficulty": 2, "estimated_time_sec": 45,
        "knowledge_point_codes": ["CHN-COMP-B04"],
        "hints": ["'转'指故事的转折点，使情节跌宕起伏。"],
    },

    # === Composition: Module C ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-C1-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n以下哪种不是景物描写的技巧？",
        "options": {"A": "多感官描写", "B": "动静结合", "C": "列数字说明", "D": "借景抒情"},
        "correct_answer": "C", "difficulty": 2, "estimated_time_sec": 45,
        "knowledge_point_codes": ["CHN-COMP-C01"],
        "hints": ["'列数字说明'是说明文的写法。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-C2-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n「托物言志」的意思是？",
        "options": {
            "A": "通过描写物品来记叙事情",
            "B": "通过描写物品来表达自己的志向或品格",
            "C": "通过描写物品来说明它的功能",
            "D": "通过描写物品来议论道理",
        },
        "correct_answer": "B", "difficulty": 2, "estimated_time_sec": 45,
        "knowledge_point_codes": ["CHN-COMP-C02"],
        "hints": ["'托物'是借物，'言志'是表达志向。"],
    },

    # === Composition: Module D ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-D1-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n看图写话的四个步骤，正确顺序是？",
        "options": {
            "A": "表达→观察→联想→构思",
            "B": "观察→联想→构思→表达",
            "C": "构思→观察→表达→联想",
            "D": "联想→观察→构思→表达",
        },
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-D01"],
        "hints": ["先看图，再想象，然后构思，最后写出来。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-D3-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n童话与寓言的最大区别是？",
        "options": {
            "A": "童话有魔法，寓言没有",
            "B": "寓言有明确的寓意或道理",
            "C": "童话是外国的，寓言是中国的",
            "D": "童话短，寓言长",
        },
        "correct_answer": "B", "difficulty": 2, "estimated_time_sec": 45,
        "knowledge_point_codes": ["CHN-COMP-D03"],
        "hints": ["寓言通过故事传达一个道理或教训。"],
    },

    # === Composition: Module E ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-E1-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n读书笔记的三要素是？",
        "options": {
            "A": "摘抄+感想+联想",
            "B": "题目+作者+内容",
            "C": "好词+好句+好段",
            "D": "开头+中间+结尾",
        },
        "correct_answer": "A", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-E01"],
        "hints": ["读书笔记要：摘抄好内容、写感想、做联想。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-E2-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n书信的正确格式顺序是？",
        "options": {
            "A": "称呼→正文→问候语→祝语→署名→日期",
            "B": "称呼→问候语→正文→祝语→署名→日期",
            "C": "正文→称呼→问候语→祝语→署名→日期",
            "D": "称呼→问候语→正文→日期→署名→祝语",
        },
        "correct_answer": "B", "difficulty": 2, "estimated_time_sec": 45,
        "knowledge_point_codes": ["CHN-COMP-E02"],
        "hints": ["书信六部分：称呼、问候语、正文、祝语、署名、日期。"],
    },

    # === Composition: Module F ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-F1-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n审题时「抓关键词」的主要目的是？",
        "options": {
            "A": "让字数更多",
            "B": "准确理解题目要求，避免偏题",
            "C": "让作文看起来更高级",
            "D": "方便使用修辞手法",
        },
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-F01"],
        "hints": ["审题的核心是准确理解题目要求。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-F4-P1",
        "subject": "chn_composition", "format": "mcq",
        "question_markdown": "## 写作知识\n\n写作考试的推荐时间分配是？",
        "options": {
            "A": "审题15分+写作25分",
            "B": "审题5分+构思5分+写作20分",
            "C": "写作30分+检查10分",
            "D": "构思10分+写作20分",
        },
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-COMP-F04"],
        "hints": ["审题5分+构思5分+写作20分是最合理的分配。"],
    },

    # === Poetry: Module A ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PA1-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n五言绝句的朗读节奏通常是？",
        "options": {"A": "二一二", "B": "二二一", "C": "一二二", "D": "一一三"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-A01"],
        "hints": ["五言诗的节奏是'二二一'，如：床前/明月/光。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PA3-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 诗歌意象\n\n古诗中「月亮」通常代表什么含义？",
        "options": {"A": "团圆", "B": "思乡", "C": "离别", "D": "坚强"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-A03"],
        "hints": ["举头望明月，低头思故乡。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PA4-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n「飞流直下三千尺」使用了什么修辞手法？",
        "options": {"A": "比喻", "B": "拟人", "C": "排比", "D": "夸张"},
        "correct_answer": "D", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-A04"],
        "hints": ["'三千尺'是极度夸大的说法。"],
    },

    # === Poetry: Module B ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PB1-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n「春眠不觉晓，处处闻啼鸟」出自哪首诗？",
        "options": {"A": "《忆江南》", "B": "《春晓》", "C": "《村居》", "D": "《绝句》"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 20,
        "knowledge_point_codes": ["CHN-P-B01"],
        "hints": ["诗名就在'春眠不觉晓'这一句里。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PB3-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n「停车坐爱枫林晚，霜叶红于二月花」描写的是哪个季节？",
        "options": {"A": "春天", "B": "夏天", "C": "秋天", "D": "冬天"},
        "correct_answer": "C", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-B03"],
        "hints": ["'枫林''霜叶'是秋天的标志。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PB4-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词默写\n\n「千山鸟飞绝，万径人踪灭」出自哪首诗？",
        "options": {"A": "《梅花》", "B": "《江雪》", "C": "《白雪歌》", "D": "《绝句》"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-B04"],
        "hints": ["这首诗写的是雪中的孤寂景象。"],
    },

    # === Poetry: Module C ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PC1-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n「飞流直下三千尺，疑是银河落九天」描写的是哪里的景观？",
        "options": {"A": "黄河", "B": "庐山瀑布", "C": "天门山", "D": "西湖"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-C01"],
        "hints": ["这首诗的题目是《望庐山瀑布》。"],
    },

    # === Poetry: Module D ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PD1-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n「独在异乡为异客，每逢佳节倍思亲」表达了什么情感？",
        "options": {"A": "爱国", "B": "思乡", "C": "送别", "D": "喜悦"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-D01"],
        "hints": ["'思亲'就是思念家乡的亲人。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PD2-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 诗歌意象\n\n古诗中「柳」通常代表什么含义？",
        "options": {"A": "春天", "B": "离别", "C": "坚强", "D": "高洁"},
        "correct_answer": "B", "difficulty": 2, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-D02"],
        "hints": ["'柳'与'留'谐音，古人折柳送别。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PD3-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n「王师北定中原日，家祭无忘告乃翁」的作者是？",
        "options": {"A": "王昌龄", "B": "陆游", "C": "林升", "D": "李清照"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-D03"],
        "hints": ["这首诗是陆游的《示儿》。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PD4-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n「千磨万击还坚劲，任尔东西南北风」描写的是什么植物？",
        "options": {"A": "梅花", "B": "竹子", "C": "松树", "D": "菊花"},
        "correct_answer": "B", "difficulty": 2, "estimated_time_sec": 30,
        "knowledge_point_codes": ["CHN-P-D04"],
        "hints": ["这首诗是郑燮的《竹石》。"],
    },

    # === Poetry: Module E ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PE1-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n李白被称为？",
        "options": {"A": "诗圣", "B": "诗仙", "C": "诗佛", "D": "诗鬼"},
        "correct_answer": "B", "difficulty": 1, "estimated_time_sec": 20,
        "knowledge_point_codes": ["CHN-P-E01"],
        "hints": ["李白诗风浪漫飘逸，被称为'诗仙'。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PE2-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 古诗词\n\n杜甫和李白在诗歌风格上的主要区别是？",
        "options": {
            "A": "李白是浪漫主义，杜甫是现实主义",
            "B": "李白是现实主义，杜甫是浪漫主义",
            "C": "两人都是浪漫主义",
            "D": "两人都是现实主义",
        },
        "correct_answer": "A", "difficulty": 2, "estimated_time_sec": 45,
        "knowledge_point_codes": ["CHN-P-E02"],
        "hints": ["李白飘逸奔放，杜甫沉郁顿挫。"],
    },

    # === Poetry: Module F ===
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PF2-P1",
        "subject": "chn_poetry", "format": "fill_blank",
        "question_markdown": "## 默写填空\n\n「春眠不觉晓，处处闻___鸟。」请填入正确的字。",
        "options": {"A": "啼", "B": "鸣", "C": "叫", "D": "唱"},
        "correct_answer": "A", "difficulty": 1, "estimated_time_sec": 20,
        "knowledge_point_codes": ["CHN-P-F02"],
        "hints": ["原诗是「处处闻啼鸟」。"],
    },
    {
        "source": "校内", "source_year": 2024, "source_code": "CHN-PF3-P1",
        "subject": "chn_poetry", "format": "mcq",
        "question_markdown": "## 诗歌鉴赏\n\n「两个黄鹂鸣翠柳，一行白鹭上青天」中，哪组词构成了对仗？",
        "options": {"A": "两个 — 青天", "B": "黄鹂 — 一行", "C": "黄鹂 — 白鹭", "D": "翠柳 — 上青"},
        "correct_answer": "C", "difficulty": 2, "estimated_time_sec": 60,
        "knowledge_point_codes": ["CHN-P-F03"],
        "hints": ["黄鹂和白鹭都是鸟类名词，颜色+鸟名，词性相同。"],
    },
]
