"""AMC 8 problem seed data — 55 realistic problems across 5 categories."""

PROBLEMS = [
    # ──── 数的运算 (Integer Operations) — 15 problems ────
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-01",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算：$4 + (6 \\times 2) - 3$ 的值是多少？",
        "options": {"A": "11", "B": "13", "C": "15", "D": "17", "E": "19"},
        "correct_answer": "B",
        "difficulty": 1,
        "estimated_time_sec": 30,
        "hints": {
            "1": "先算乘法，再算加减。",
            "2": "6 × 2 = 12，然后 4 + 12 = 16，最后 16 - 3 = 13。",
            "3": "答案是 13。",
        },
        "misconceptions": {
            "common_wrong_1": "选A的人可能从左到右依次计算，先算4+6=10，再算10×2=20，20-3=17选了D。",
        },
        "step_decomposition": {"step_1": "先计算括号内的乘法：6 × 2 = 12", "step_2": "再加：4 + 12 = 16", "step_3": "最后减：16 - 3 = 13"},
    },
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-02",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $1 + 2 + 3 + \\cdots + 100$ 的值。",
        "options": {"A": "4950", "B": "5000", "C": "5050", "D": "5100", "E": "5150"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "这是一个等差数列求和问题。",
            "2": "等差数列求和公式：$S = \\frac{n(a_1 + a_n)}{2}$",
            "3": "代入 n=100, a₁=1, a₁₀₀=100，得 S = 5050。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能算成 n(n-1)/2 = 4950。"},
        "step_decomposition": {"step_1": "识别等差数列：首项=1，末项=100，项数=100", "step_2": "套用公式：S = 100×(1+100)/2", "step_3": "计算：100×101/2 = 5050"},
    },
    {
        "source": "AMC8",
        "source_year": 2021,
        "source_code": "AMC8-2021-03",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "三个连续整数的和是 63，这三个数中最大的数是多少？",
        "options": {"A": "20", "B": "21", "C": "22", "D": "23", "E": "24"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "设三个连续整数为 n-1, n, n+1。",
            "2": "它们的和 = 3n = 63，所以 n = 21。",
            "3": "最大的数是 n+1 = 22。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能把中间数当成最大数。"},
        "step_decomposition": {"step_1": "设中间的整数为 n，则三个数为 n-1, n, n+1", "step_2": "列方程：(n-1)+n+(n+1) = 3n = 63", "step_3": "解得 n=21，最大数为 22"},
    },
    {
        "source": "AMC8",
        "source_year": 2018,
        "source_code": "AMC8-2018-04",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $2^3 \\times 3^2$ 的值。",
        "options": {"A": "36", "B": "48", "C": "64", "D": "72", "E": "81"},
        "correct_answer": "D",
        "difficulty": 1,
        "estimated_time_sec": 30,
        "hints": {
            "1": "分别计算每个幂的值。",
            "2": "2³ = 8, 3² = 9。",
            "3": "8 × 9 = 72。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能算成 2×3 × 3×2 = 36。"},
        "step_decomposition": {"step_1": "计算 2³ = 8", "step_2": "计算 3² = 9", "step_3": "相乘：8 × 9 = 72"},
    },
    {
        "source": "AMC8",
        "source_year": 2022,
        "source_code": "AMC8-2022-05",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "从 1 到 2022 的所有整数中，有多少个是 3 的倍数？",
        "options": {"A": "670", "B": "673", "C": "674", "D": "675", "E": "676"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "用除法计算：2022 ÷ 3。",
            "2": "2022 ÷ 3 = 674，余数为0。",
            "3": "所以恰好有 674 个。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能用 floor(2022/3) 但算错了。"},
        "step_decomposition": {"step_1": "3的倍数有 3, 6, 9, ..., 2022", "step_2": "项数 = 2022 / 3 = 674", "step_3": "答案为 674"},
    },
    {
        "source": "AMC8",
        "source_year": 2017,
        "source_code": "AMC8-2017-06",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "若 $a \\star b = a^2 - b^2$，求 $5 \\star 3$ 的值。",
        "options": {"A": "8", "B": "10", "C": "16", "D": "22", "E": "34"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "代入定义：a★b = a² - b²。",
            "2": "5★3 = 5² - 3² = 25 - 9 = 16。",
            "3": "答案是 16。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能算成 (5-3)² = 4 或 5×3-3 = 12。"},
        "step_decomposition": {"step_1": "根据定义，5★3 = 5² - 3²", "step_2": "计算 5² = 25, 3² = 9", "step_3": "25 - 9 = 16"},
    },
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-07",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $(-3) \\times (-4) + (-5) \\times 2$ 的值。",
        "options": {"A": "2", "B": "7", "C": "12", "D": "-22", "E": "22"},
        "correct_answer": "A",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "注意负数乘法的符号：负×负=正。",
            "2": "(-3)×(-4) = 12, (-5)×2 = -10。",
            "3": "12 + (-10) = 2。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能两处符号都弄错了。"},
        "step_decomposition": {"step_1": "计算 (-3)×(-4) = 12", "step_2": "计算 (-5)×2 = -10", "step_3": "相加：12 + (-10) = 2"},
    },
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-08",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个两位数，个位数字是十位数字的 2 倍，且两个数字之和为 9。这个两位数是多少？",
        "options": {"A": "18", "B": "27", "C": "36", "D": "45", "E": "63"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "设十位数字为 d，个位数字为 2d。",
            "2": "d + 2d = 9，所以 d = 3。",
            "3": "十位=3，个位=6，这个数是 36。",
        },
        "misconceptions": {"common_wrong_1": "选C的人正确。选其他选项的人可能没检查两个条件。"},
        "step_decomposition": {"step_1": "设十位数字为 d，则个位为 2d", "step_2": "列方程 d + 2d = 9，解得 d = 3", "step_3": "这个两位数是 36"},
    },
    {
        "source": "AMC8",
        "source_year": 2023,
        "source_code": "AMC8-2023-09",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $999 \\times 1001$ 的值。",
        "options": {"A": "999000", "B": "999999", "C": "1000000", "D": "1000999", "E": "999899"},
        "correct_answer": "E",
        "difficulty": 3,
        "estimated_time_sec": 60,
        "hints": {
            "1": "利用平方差公式：(a-b)(a+b) = a²-b²。",
            "2": "999×1001 = (1000-1)(1000+1) = 1000²-1。",
            "3": "= 1000000 - 1 = 999999。",
        },
        "misconceptions": {"common_wrong_1": "直接乘法容易出错。"},
        "step_decomposition": {"step_1": "识别 999 = 1000-1, 1001 = 1000+1", "step_2": "用平方差公式：1000² - 1² = 999999", "step_3": "答案为 999999"},
    },
    {
        "source": "AMC8",
        "source_year": 2016,
        "source_code": "AMC8-2016-10",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "正整数 $n$ 满足 $n! = 8 \\times 7!$，求 $n$。",
        "options": {"A": "6", "B": "7", "C": "8", "D": "9", "E": "10"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "注意 n! = n × (n-1)!。",
            "2": "如果 n = 8，则 8! = 8 × 7!。",
            "3": "所以 n = 8。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能没注意题目是 n! = 8×7!。"},
        "step_decomposition": {"step_1": "由 n! = 8 × 7!", "step_2": "因为 n! = n × (n-1)!", "step_3": "所以 n = 8"},
    },
    {
        "source": "AMC8",
        "source_year": 2021,
        "source_code": "AMC8-2021-11",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "从 1 到 100 的所有整数中，既不是 2 的倍数也不是 3 的倍数的整数有多少个？",
        "options": {"A": "30", "B": "33", "C": "34", "D": "50", "E": "67"},
        "correct_answer": "B",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "用容斥原理：先分别算 2 的倍数和 3 的倍数的个数。",
            "2": "2的倍数50个，3的倍数33个，6的倍数16个。至少被一个整除的有 50+33-16=67 个。",
            "3": "都不被整除的：100 - 67 = 33 个。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能只排除了2的倍数。"},
        "step_decomposition": {"step_1": "计算 2 的倍数：50 个；3 的倍数：33 个；6 的倍数：16 个", "step_2": "容斥：50 + 33 - 16 = 67", "step_3": "100 - 67 = 33"},
    },
    {
        "source": "AMC8",
        "source_year": 2018,
        "source_code": "AMC8-2018-12",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个正整数的立方是 3375，这个正整数是多少？",
        "options": {"A": "10", "B": "12", "C": "15", "D": "18", "E": "25"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "3375 的个位是 5，所以答案的个位也是 5。",
            "2": "15³ = 3375。",
            "3": "答案是 15。",
        },
        "misconceptions": {"common_wrong_1": "选E的人可能用平方根算了。"},
        "step_decomposition": {"step_1": "由个位是5，尝试个位为5的数", "step_2": "15³ = 15×15×15 = 225×15 = 3375", "step_3": "答案是 15"},
    },
    {
        "source": "AMC8",
        "source_year": 2022,
        "source_code": "AMC8-2022-13",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $2022 - 2021 + 2020 - 2019 + \\cdots + 2 - 1$ 的值。",
        "options": {"A": "1010", "B": "1011", "C": "1012", "D": "2022", "E": "1010.5"},
        "correct_answer": "B",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "两两配对：(2022-2021) + (2020-2019) + ... + (2-1)。",
            "2": "每对等于 1，共有 1011 对。",
            "3": "答案是 1011。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能少算了一对。"},
        "step_decomposition": {"step_1": "配对：(2022-2021)+(2020-2019)+...+(2-1)", "step_2": "每对 = 1，共 2022/2 = 1011 对", "step_3": "总和 = 1011"},
    },
    {
        "source": "AMC8",
        "source_year": 2023,
        "source_code": "AMC8-2023-14",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "如果 $2^a = 32$ 且 $3^b = 81$，求 $a + b$ 的值。",
        "options": {"A": "7", "B": "8", "C": "9", "D": "10", "E": "11"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "把32和81分别表示为2和3的幂。",
            "2": "2⁵ = 32，3⁴ = 81。",
            "3": "a=5, b=4, a+b = 9。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能算成 5+5=10。"},
        "step_decomposition": {"step_1": "2ᵃ = 32 → a = 5", "step_2": "3ᵇ = 81 → b = 4", "step_3": "a + b = 9"},
    },
    {
        "source": "AMC8",
        "source_year": 2017,
        "source_code": "AMC8-2017-15",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "求满足 $\\frac{24}{n}$ 是正整数的最小正整数 $n$ 的值。",
        "options": {"A": "1", "B": "2", "C": "3", "D": "4", "E": "6"},
        "correct_answer": "A",
        "difficulty": 1,
        "estimated_time_sec": 30,
        "hints": {
            "1": "24/n 是正整数意味着 n 是 24 的正因数。",
            "2": "24 的正因数有：1, 2, 3, 4, 6, 8, 12, 24。",
            "3": "最小的是 1。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能忽略了1也是因数。"},
        "step_decomposition": {"step_1": "n 必须是 24 的正因数", "step_2": "24 的正因数：1, 2, 3, 4, 6, 8, 12, 24", "step_3": "最小为 1"},
    },
    # ──── 分数运算 (Fraction Operations) — 10 problems ────
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-16",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $\\frac{3}{4} + \\frac{5}{6} - \\frac{1}{3}$ 的值。",
        "options": {"A": "$\\frac{5}{4}$", "B": "$\\frac{7}{6}$", "C": "$\\frac{11}{12}$", "D": "$\\frac{5}{3}$", "E": "$\\frac{3}{2}$"},
        "correct_answer": "A",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "先找最小公倍数通分：4, 6, 3 的最小公倍数是 12。",
            "2": "= 9/12 + 10/12 - 4/12 = 15/12。",
            "3": "约分：15/12 = 5/4。",
        },
        "misconceptions": {"common_wrong_1": "选C的人可能忘记约分或者只减了一个。"},
        "step_decomposition": {"step_1": "通分：3/4 = 9/12, 5/6 = 10/12, 1/3 = 4/12", "step_2": "计算：9/12 + 10/12 - 4/12 = 15/12", "step_3": "约分：15/12 = 5/4"},
    },
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-17",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $\\left(\\frac{1}{2} \\times \\frac{2}{3}\\right) \\div \\left(\\frac{1}{4} \\times \\frac{4}{5}\\right)$ 的值。",
        "options": {"A": "$\\frac{1}{3}$", "B": "$\\frac{5}{3}$", "C": "$\\frac{3}{5}$", "D": "$1$", "E": "$\\frac{2}{5}$"},
        "correct_answer": "B",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "分别计算分子和分母的乘积。",
            "2": "分子：1/2 × 2/3 = 1/3。分母：1/4 × 4/5 = 1/5。",
            "3": "1/3 ÷ 1/5 = 1/3 × 5 = 5/3。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能只算了分子部分。"},
        "step_decomposition": {"step_1": "分子：1/2 × 2/3 = 1/3", "step_2": "分母：1/4 × 4/5 = 1/5", "step_3": "1/3 ÷ 1/5 = 5/3"},
    },
    {
        "source": "AMC8",
        "source_year": 2021,
        "source_code": "AMC8-2021-18",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个数的 $\\frac{2}{5}$ 等于 24，这个数是多少？",
        "options": {"A": "48", "B": "50", "C": "60", "D": "72", "E": "96"},
        "correct_answer": "C",
        "difficulty": 1,
        "estimated_time_sec": 45,
        "hints": {
            "1": "设这个数为 x，则 (2/5)x = 24。",
            "2": "x = 24 × (5/2) = 60。",
            "3": "答案是 60。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能算成 24 × 2 = 48。"},
        "step_decomposition": {"step_1": "设 (2/5)x = 24", "step_2": "两边乘 5/2：x = 24 × 5/2", "step_3": "x = 60"},
    },
    {
        "source": "AMC8",
        "source_year": 2018,
        "source_code": "AMC8-2018-19",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "将 $\\frac{7}{12}$、$\\frac{5}{8}$、$\\frac{3}{5}$ 从小到大排列，中间的数是哪个？",
        "options": {"A": "$\\frac{7}{12}$", "B": "$\\frac{5}{8}$", "C": "$\\frac{3}{5}$", "D": "无法确定", "E": "$\\frac{1}{2}$"},
        "correct_answer": "C",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "通分为相同的分母比较，或转成小数。",
            "2": "7/12 ≈ 0.583, 3/5 = 0.6, 5/8 = 0.625。",
            "3": "排序：7/12 < 3/5 < 5/8，中间的是 3/5。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能没有通分，直接比较了分母。"},
        "step_decomposition": {"step_1": "通分到 120：7/12=70/120, 3/5=72/120, 5/8=75/120", "step_2": "排序：7/12 < 3/5 < 5/8", "step_3": "中间的是 3/5"},
    },
    {
        "source": "AMC8",
        "source_year": 2022,
        "source_code": "AMC8-2022-20",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "如果 $\\frac{a}{b} = \\frac{3}{5}$ 且 $a + b = 40$，求 $a$ 的值。",
        "options": {"A": "10", "B": "12", "C": "15", "D": "18", "E": "25"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "由 a/b = 3/5，设 a = 3k, b = 5k。",
            "2": "a + b = 8k = 40，所以 k = 5。",
            "3": "a = 3 × 5 = 15。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能设 k=6 算错了。"},
        "step_decomposition": {"step_1": "设 a = 3k, b = 5k", "step_2": "3k + 5k = 8k = 40, k = 5", "step_3": "a = 3 × 5 = 15"},
    },
    {
        "source": "AMC8",
        "source_year": 2017,
        "source_code": "AMC8-2017-21",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一根绳子先剪去 $\\frac{1}{3}$，再剪去剩下的 $\\frac{1}{4}$，还剩多少比例？",
        "options": {"A": "$\\frac{1}{2}$", "B": "$\\frac{5}{12}$", "C": "$\\frac{7}{12}$", "D": "$\\frac{2}{3}$", "E": "$\\frac{3}{4}$"},
        "correct_answer": "A",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "第一次剪去 1/3，剩下 2/3。",
            "2": "第二次剪去 (2/3)×(1/4) = 1/6。",
            "3": "剩余：2/3 - 1/6 = 4/6 - 1/6 = 3/6 = 1/2。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能直接算 1/3 + 1/4 然后用 1 减。"},
        "step_decomposition": {"step_1": "第一次剪去后剩余：1 - 1/3 = 2/3", "step_2": "第二次剪去：(2/3)×(1/4) = 1/6", "step_3": "剩余：2/3 - 1/6 = 1/2"},
    },
    {
        "source": "AMC8",
        "source_year": 2023,
        "source_code": "AMC8-2023-22",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "计算 $\\frac{1}{1 \\times 2} + \\frac{1}{2 \\times 3} + \\frac{1}{3 \\times 4} + \\cdots + \\frac{1}{99 \\times 100}$ 的值。",
        "options": {"A": "$\\frac{98}{99}$", "B": "$\\frac{99}{100}$", "C": "$1$", "D": "$\\frac{100}{99}$", "E": "$\\frac{50}{51}$"},
        "correct_answer": "B",
        "difficulty": 4,
        "estimated_time_sec": 120,
        "hints": {
            "1": "用裂项：1/(n(n+1)) = 1/n - 1/(n+1)。",
            "2": "原式 = (1-1/2) + (1/2-1/3) + ... + (1/99-1/100)。",
            "3": "大部分项消掉了，只剩 1 - 1/100 = 99/100。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能少算了一项。"},
        "step_decomposition": {"step_1": "裂项：1/(n(n+1)) = 1/n - 1/(n+1)", "step_2": "展开后中间项全部相消", "step_3": "剩余 1 - 1/100 = 99/100"},
    },
    {
        "source": "AMC8",
        "source_year": 2016,
        "source_code": "AMC8-2016-23",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "小华用 $\\frac{1}{3}$ 的时间做作业，$\\frac{1}{4}$ 的时间看书，$\\frac{1}{6}$ 的时间运动。他还剩下多少比例的时间？",
        "options": {"A": "$\\frac{1}{12}$", "B": "$\\frac{1}{4}$", "C": "$\\frac{5}{12}$", "D": "$\\frac{1}{2}$", "E": "$\\frac{7}{12}$"},
        "correct_answer": "B",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "先算已用时间的比例：1/3 + 1/4 + 1/6。",
            "2": "通分到12：4/12 + 3/12 + 2/12 = 9/12 = 3/4。",
            "3": "剩余：1 - 3/4 = 1/4。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能计算有误。"},
        "step_decomposition": {"step_1": "已用比例：1/3 + 1/4 + 1/6 = 9/12 = 3/4", "step_2": "剩余：1 - 3/4 = 1/4", "step_3": "答案是 1/4"},
    },
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-24",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "化简 $\\frac{\\frac{1}{2} + \\frac{1}{3}}{\\frac{1}{2} - \\frac{1}{3}}$ 的结果。",
        "options": {"A": "$\\frac{1}{5}$", "B": "$1$", "C": "$2$", "D": "$3$", "E": "$5$"},
        "correct_answer": "E",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "分别计算分子和分母。",
            "2": "分子：1/2+1/3 = 5/6。分母：1/2-1/3 = 1/6。",
            "3": "(5/6)/(1/6) = 5。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能分子分母直接除没通分。"},
        "step_decomposition": {"step_1": "分子：1/2 + 1/3 = 5/6", "step_2": "分母：1/2 - 1/3 = 1/6", "step_3": "(5/6) ÷ (1/6) = 5"},
    },
    # ──── 几何基础 (Geometry Basics) — 10 problems ────
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-25",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个长方形的长是 12 cm，宽是 5 cm。它的对角线长度是多少 cm？",
        "options": {"A": "10", "B": "11", "C": "12", "D": "13", "E": "15"},
        "correct_answer": "D",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "用勾股定理：对角线² = 长² + 宽²。",
            "2": "d² = 12² + 5² = 144 + 25 = 169。",
            "3": "d = √169 = 13。",
        },
        "misconceptions": {"common_wrong_1": "选C的人可能只算了 12+5-4 或猜了。"},
        "step_decomposition": {"step_1": "勾股定理：d² = 12² + 5²", "step_2": "d² = 144 + 25 = 169", "step_3": "d = 13"},
    },
    {
        "source": "AMC8",
        "source_year": 2021,
        "source_code": "AMC8-2021-26",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个圆的面积是 $36\\pi$，它的周长是多少？",
        "options": {"A": "$6\\pi$", "B": "$8\\pi$", "C": "$10\\pi$", "D": "$12\\pi$", "E": "$18\\pi$"},
        "correct_answer": "D",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "面积 = πr²，所以 πr² = 36π，r² = 36。",
            "2": "r = 6。",
            "3": "周长 = 2πr = 12π。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能只算了半径 r=6 没乘 2。"},
        "step_decomposition": {"step_1": "由 πr² = 36π 得 r = 6", "step_2": "周长 = 2πr = 2π×6", "step_3": "= 12π"},
    },
    {
        "source": "AMC8",
        "source_year": 2018,
        "source_code": "AMC8-2018-27",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个正方体的棱长为 3，它的表面积是多少？",
        "options": {"A": "27", "B": "36", "C": "45", "D": "54", "E": "81"},
        "correct_answer": "D",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "正方体有 6 个面。",
            "2": "每个面的面积 = 3 × 3 = 9。",
            "3": "表面积 = 6 × 9 = 54。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能算成 4 个面。"},
        "step_decomposition": {"step_1": "每个面的面积 = 3² = 9", "step_2": "正方体有 6 个面", "step_3": "表面积 = 6 × 9 = 54"},
    },
    {
        "source": "AMC8",
        "source_year": 2022,
        "source_code": "AMC8-2022-28",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个三角形的三个内角之比为 $2:3:4$，最大的角是多少度？",
        "options": {"A": "60°", "B": "70°", "C": "80°", "D": "90°", "E": "100°"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "三角形内角和为 180°。",
            "2": "设角度为 2x, 3x, 4x，则 9x = 180°。",
            "3": "x = 20°，最大角 = 4×20° = 80°。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能把4x当成直角了。"},
        "step_decomposition": {"step_1": "设三个角为 2x, 3x, 4x", "step_2": "2x + 3x + 4x = 180°, x = 20°", "step_3": "最大角 = 4 × 20° = 80°"},
    },
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-29",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "如图，一个大正方形的边长为 8，在其中挖去一个边长为 3 的小正方形，剩余部分的面积是多少？",
        "options": {"A": "51", "B": "55", "C": "61", "D": "64", "E": "73"},
        "correct_answer": "B",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "大正方形面积 - 小正方形面积。",
            "2": "8² - 3² = 64 - 9 = 55。",
            "3": "答案是 55。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能忘记减去小正方形。"},
        "step_decomposition": {"step_1": "大正方形面积 = 8² = 64", "step_2": "小正方形面积 = 3² = 9", "step_3": "剩余 = 64 - 9 = 55"},
    },
    {
        "source": "AMC8",
        "source_year": 2023,
        "source_code": "AMC8-2023-30",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个梯形的上底为 4，下底为 10，高为 6，它的面积是多少？",
        "options": {"A": "30", "B": "36", "C": "42", "D": "48", "E": "60"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "梯形面积公式：S = (上底+下底) × 高 ÷ 2。",
            "2": "S = (4+10) × 6 ÷ 2 = 14 × 3 = 42。",
            "3": "答案是 42。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能忘记除以2。"},
        "step_decomposition": {"step_1": "套用公式 S = (a+b)h/2", "step_2": "S = (4+10)×6/2", "step_3": "S = 42"},
    },
    {
        "source": "AMC8",
        "source_year": 2017,
        "source_code": "AMC8-2017-31",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个圆柱的底面半径为 3，高为 10，它的体积是多少？（用 $\\pi$ 表示）",
        "options": {"A": "$30\\pi$", "B": "$60\\pi$", "C": "$90\\pi$", "D": "$120\\pi$", "E": "$180\\pi$"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "圆柱体积 V = πr²h。",
            "2": "V = π × 3² × 10 = π × 9 × 10。",
            "3": "V = 90π。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能用 2πrh 算了侧面积。"},
        "step_decomposition": {"step_1": "V = πr²h", "step_2": "= π × 9 × 10", "step_3": "= 90π"},
    },
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-32",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个正六边形的边长为 2，它的面积是多少？",
        "options": {"A": "$6$", "B": "$6\\sqrt{3}$", "C": "$12$", "D": "$12\\sqrt{3}$", "E": "$24$"},
        "correct_answer": "B",
        "difficulty": 4,
        "estimated_time_sec": 120,
        "hints": {
            "1": "正六边形可以分成 6 个等边三角形。",
            "2": "等边三角形面积 = (√3/4) × a² = (√3/4) × 4 = √3。",
            "3": "总面积 = 6 × √3 = 6√3。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能多乘了2。"},
        "step_decomposition": {"step_1": "正六边形 = 6 个等边三角形", "step_2": "每个等边三角形面积 = √3", "step_3": "总面积 = 6√3"},
    },
    {
        "source": "AMC8",
        "source_year": 2021,
        "source_code": "AMC8-2021-33",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个直角三角形的两条直角边分别为 8 和 15，斜边上的高是多少？",
        "options": {"A": "$\\frac{120}{17}$", "B": "$\\frac{60}{17}$", "C": "$8$", "D": "$\\frac{15}{2}$", "E": "$7$"},
        "correct_answer": "A",
        "difficulty": 4,
        "estimated_time_sec": 120,
        "hints": {
            "1": "先求斜边：c = √(64+225) = √289 = 17。",
            "2": "面积 = (1/2) × 8 × 15 = 60 = (1/2) × 17 × h。",
            "3": "h = 120/17。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能用了一条边代替斜边。"},
        "step_decomposition": {"step_1": "斜边 c = √(8² + 15²) = 17", "step_2": "面积法：60 = (1/2)×17×h", "step_3": "h = 120/17"},
    },
    {
        "source": "AMC8",
        "source_year": 2022,
        "source_code": "AMC8-2022-34",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个扇形的半径为 6，圆心角为 $120°$，它的面积是多少？（用 $\\pi$ 表示）",
        "options": {"A": "$6\\pi$", "B": "$9\\pi$", "C": "$12\\pi$", "D": "$18\\pi$", "E": "$36\\pi$"},
        "correct_answer": "C",
        "difficulty": 3,
        "estimated_time_sec": 60,
        "hints": {
            "1": "扇形面积 = (圆心角/360°) × πr²。",
            "2": "= (120/360) × π × 36 = (1/3) × 36π。",
            "3": "= 12π。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能用错了圆心角比例。"},
        "step_decomposition": {"step_1": "扇形面积 = (θ/360)πr²", "step_2": "= (120/360) × π × 36", "step_3": "= 12π"},
    },
    # ──── 计数与概率 (Counting & Probability) — 10 problems ────
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-35",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "从 1 到 10 的整数中，随机选一个数，它是偶数的概率是多少？",
        "options": {"A": "$\\frac{1}{5}$", "B": "$\\frac{2}{5}$", "C": "$\\frac{1}{2}$", "D": "$\\frac{3}{5}$", "E": "$\\frac{2}{3}$"},
        "correct_answer": "C",
        "difficulty": 1,
        "estimated_time_sec": 30,
        "hints": {
            "1": "1到10的偶数有：2, 4, 6, 8, 10。",
            "2": "共5个偶数，总共有10个数。",
            "3": "概率 = 5/10 = 1/2。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能只算了偶数但总数算错。"},
        "step_decomposition": {"step_1": "偶数：2, 4, 6, 8, 10 共5个", "step_2": "总共有10个整数", "step_3": "P = 5/10 = 1/2"},
    },
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-36",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "同时掷两枚均匀的骰子，两枚骰子点数之和为 7 的概率是多少？",
        "options": {"A": "$\\frac{1}{12}$", "B": "$\\frac{1}{9}$", "C": "$\\frac{1}{6}$", "D": "$\\frac{5}{36}$", "E": "$\\frac{7}{36}$"},
        "correct_answer": "C",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "和为7的组合：(1,6), (2,5), (3,4), (4,3), (5,2), (6,1)。",
            "2": "共 6 种有利情况，总共 36 种可能。",
            "3": "概率 = 6/36 = 1/6。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能漏数了几种组合。"},
        "step_decomposition": {"step_1": "列举和为7的组合：6种", "step_2": "总可能数：6×6 = 36", "step_3": "P = 6/36 = 1/6"},
    },
    {
        "source": "AMC8",
        "source_year": 2021,
        "source_code": "AMC8-2021-37",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "5 个人站成一排照相，一共有多少种不同的排列方式？",
        "options": {"A": "25", "B": "60", "C": "120", "D": "240", "E": "720"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "n 个人的排列数 = n!。",
            "2": "5! = 5 × 4 × 3 × 2 × 1。",
            "3": "5! = 120。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能算成 P(5,3)。"},
        "step_decomposition": {"step_1": "排列数 = 5!", "step_2": "5! = 120", "step_3": "答案为 120"},
    },
    {
        "source": "AMC8",
        "source_year": 2022,
        "source_code": "AMC8-2022-38",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "从 6 名男生和 4 名女生中选出 2 名学生，恰好一男一女的选法有多少种？",
        "options": {"A": "10", "B": "20", "C": "24", "D": "30", "E": "40"},
        "correct_answer": "C",
        "difficulty": 3,
        "estimated_time_sec": 60,
        "hints": {
            "1": "选1男1女：C(6,1) × C(4,1)。",
            "2": "6 × 4 = 24。",
            "3": "答案是 24。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能算成 C(10,2) 但只取了一部分。"},
        "step_decomposition": {"step_1": "选1名男生：C(6,1) = 6", "step_2": "选1名女生：C(4,1) = 4", "step_3": "6 × 4 = 24"},
    },
    {
        "source": "AMC8",
        "source_year": 2018,
        "source_code": "AMC8-2018-39",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个袋子里有 3 个红球、4 个蓝球和 5 个绿球。随机取出一个球，它是红色或蓝色的概率是多少？",
        "options": {"A": "$\\frac{1}{3}$", "B": "$\\frac{7}{12}$", "C": "$\\frac{1}{2}$", "D": "$\\frac{2}{3}$", "E": "$\\frac{3}{4}$"},
        "correct_answer": "B",
        "difficulty": 2,
        "estimated_time_sec": 45,
        "hints": {
            "1": "红球或蓝球共有 3+4 = 7 个。",
            "2": "总球数 = 3+4+5 = 12。",
            "3": "P = 7/12。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能只算了红球的概率。"},
        "step_decomposition": {"step_1": "红球+蓝球 = 7 个", "step_2": "总球数 = 12", "step_3": "P = 7/12"},
    },
    {
        "source": "AMC8",
        "source_year": 2023,
        "source_code": "AMC8-2023-40",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "用数字 1、2、3、4 可以组成多少个没有重复数字的三位数？",
        "options": {"A": "12", "B": "16", "C": "24", "D": "36", "E": "64"},
        "correct_answer": "C",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "排列问题：从4个数字中选3个排列。",
            "2": "P(4,3) = 4 × 3 × 2。",
            "3": "= 24。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能算成 C(4,3)。"},
        "step_decomposition": {"step_1": "百位：4种选择", "step_2": "十位：3种选择；个位：2种选择", "step_3": "4×3×2 = 24"},
    },
    {
        "source": "AMC8",
        "source_year": 2017,
        "source_code": "AMC8-2017-41",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "抛一枚均匀硬币 3 次，恰好出现 2 次正面的概率是多少？",
        "options": {"A": "$\\frac{1}{8}$", "B": "$\\frac{3}{8}$", "C": "$\\frac{1}{2}$", "D": "$\\frac{5}{8}$", "E": "$\\frac{7}{8}$"},
        "correct_answer": "B",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "恰好2次正面 = C(3,2) 种情况。",
            "2": "C(3,2) = 3 种：HHT, HTH, THH。",
            "3": "概率 = 3/8。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能只算了一种排列。"},
        "step_decomposition": {"step_1": "恰好2次正面的组合数：C(3,2) = 3", "step_2": "总可能数：2³ = 8", "step_3": "P = 3/8"},
    },
    {
        "source": "AMC8",
        "source_year": 2016,
        "source_code": "AMC8-2016-42",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "从 1 到 100 的整数中，含有数字 7 的整数有多少个？",
        "options": {"A": "10", "B": "18", "C": "19", "D": "20", "E": "28"},
        "correct_answer": "C",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "分类计数：个位有7（7,17,27,...,97）10个，十位有7（70,71,...,79）10个。",
            "2": "但77被重复计算了，需要减去。",
            "3": "10 + 10 - 1 = 19。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能忘记减去重复的77。"},
        "step_decomposition": {"step_1": "个位含7：7, 17, 27, ..., 97 共10个", "step_2": "十位含7：70-79 共10个，77重复", "step_3": "10 + 10 - 1 = 19"},
    },
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-43",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "从集合 $\\{1, 2, 3, 4, 5\\}$ 中任选 2 个不同的数，它们的和为偶数的概率是多少？",
        "options": {"A": "$\\frac{1}{5}$", "B": "$\\frac{2}{5}$", "C": "$\\frac{1}{2}$", "D": "$\\frac{3}{5}$", "E": "$\\frac{4}{5}$"},
        "correct_answer": "B",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "和为偶数需要两个数同奇偶。",
            "2": "两个奇数：C(3,2)=3；两个偶数：C(2,2)=1。共4种。",
            "3": "总选法：C(5,2)=10。P = 4/10 = 2/5。",
        },
        "misconceptions": {"common_wrong_1": "选C的人可能没除以总选法。"},
        "step_decomposition": {"step_1": "奇数{1,3,5}选2个：C(3,2)=3", "step_2": "偶数{2,4}选2个：C(2,2)=1；共4种", "step_3": "C(5,2)=10, P=4/10=2/5"},
    },
    # ──── 应用题 (Word Problems) — 10 problems ────
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-44",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "小明有 15 元钱，买了一本书花了 8 元，又买了一支笔花了 3 元。他还剩多少元？",
        "options": {"A": "3元", "B": "4元", "C": "5元", "D": "6元", "E": "7元"},
        "correct_answer": "B",
        "difficulty": 1,
        "estimated_time_sec": 30,
        "hints": {
            "1": "总花费 = 8 + 3 = 11 元。",
            "2": "剩余 = 15 - 11 = 4 元。",
            "3": "答案是 4 元。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能算成 15-8-4 而不是 15-8-3。"},
        "step_decomposition": {"step_1": "总花费：8 + 3 = 11 元", "step_2": "剩余：15 - 11 = 4 元", "step_3": "答案是 4 元"},
    },
    {
        "source": "AMC8",
        "source_year": 2021,
        "source_code": "AMC8-2021-45",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "甲乙两人同时从相距 60 公里的两地出发，相向而行。甲的速度是每小时 8 公里，乙的速度是每小时 12 公里。几小时后两人相遇？",
        "options": {"A": "2", "B": "3", "C": "4", "D": "5", "E": "6"},
        "correct_answer": "B",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "两人相向而行的相对速度 = 8 + 12 = 20 公里/小时。",
            "2": "相遇时间 = 60 / 20 = 3 小时。",
            "3": "答案是 3 小时。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能用了速度差。"},
        "step_decomposition": {"step_1": "相对速度 = 8 + 12 = 20 公里/时", "step_2": "时间 = 60/20 = 3 小时", "step_3": "答案是 3"},
    },
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-46",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一件商品原价 200 元，先涨价 20%，再降价 20%，现价是多少元？",
        "options": {"A": "192元", "B": "196元", "C": "200元", "D": "208元", "E": "240元"},
        "correct_answer": "A",
        "difficulty": 3,
        "estimated_time_sec": 60,
        "hints": {
            "1": "涨20%后：200 × 1.2 = 240 元。",
            "2": "再降20%：240 × 0.8 = 192 元。",
            "3": "答案是 192 元。",
        },
        "misconceptions": {"common_wrong_1": "选C的人以为涨跌抵消了。"},
        "step_decomposition": {"step_1": "涨价后：200 × 1.2 = 240", "step_2": "降价后：240 × 0.8 = 192", "step_3": "现价 192 元"},
    },
    {
        "source": "AMC8",
        "source_year": 2018,
        "source_code": "AMC8-2018-47",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个水池有两个进水管。甲管单独注满需要 6 小时，乙管单独注满需要 10 小时。两管同时开，几小时注满？",
        "options": {"A": "$3$ 小时", "B": "$3.75$ 小时", "C": "$4$ 小时", "D": "$5$ 小时", "E": "$8$ 小时"},
        "correct_answer": "B",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "甲管效率 1/6，乙管效率 1/10。",
            "2": "合开效率 = 1/6 + 1/10 = 8/30 = 4/15。",
            "3": "时间 = 15/4 = 3.75 小时。",
        },
        "misconceptions": {"common_wrong_1": "选C的人可能取了平均值 (6+10)/2 = 8，然后算错了。"},
        "step_decomposition": {"step_1": "甲管效率 = 1/6，乙管效率 = 1/10", "step_2": "合开效率 = 1/6 + 1/10 = 4/15", "step_3": "时间 = 15/4 = 3.75 小时"},
    },
    {
        "source": "AMC8",
        "source_year": 2022,
        "source_code": "AMC8-2022-48",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "小明今年 10 岁，他爸爸今年 42 岁。多少年前爸爸的年龄是小明的 5 倍？",
        "options": {"A": "1年", "B": "2年", "C": "3年", "D": "4年", "E": "5年"},
        "correct_answer": "B",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "设 x 年前，爸爸 (42-x) 岁，小明 (10-x) 岁。",
            "2": "列方程：42-x = 5(10-x)。",
            "3": "42-x = 50-5x → 4x = 8 → x = 2。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能算错了方程。"},
        "step_decomposition": {"step_1": "设 x 年前满足条件", "step_2": "42-x = 5(10-x)，解得 4x=8", "step_3": "x = 2 年前"},
    },
    {
        "source": "AMC8",
        "source_year": 2023,
        "source_code": "AMC8-2023-49",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一条路长 1200 米，甲走完全程需要 15 分钟，乙走完全程需要 20 分钟。两人同时从两端相向出发，几分钟后相遇？",
        "options": {"A": "$6$ 分钟", "B": "$\\frac{60}{7}$ 分钟", "C": "$8$ 分钟", "D": "$10$ 分钟", "E": "$12$ 分钟"},
        "correct_answer": "B",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "甲的速度 = 80 米/分，乙的速度 = 60 米/分。",
            "2": "相向而行，相对速度 = 80+60 = 140 米/分。",
            "3": "相遇时间 = 1200/140 = 60/7 分钟。",
        },
        "misconceptions": {"common_wrong_1": "选C的人可能取了速度平均值。"},
        "step_decomposition": {"step_1": "甲速 80 m/min, 乙速 60 m/min", "step_2": "相对速度 = 140 m/min", "step_3": "时间 = 1200/140 = 60/7 分钟"},
    },
    {
        "source": "AMC8",
        "source_year": 2017,
        "source_code": "AMC8-2017-50",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "鸡兔同笼，共有 35 个头、94 只脚。鸡和兔各有多少只？",
        "options": {"A": "鸡23，兔12", "B": "鸡24，兔11", "C": "鸡23，兔13", "D": "鸡25，兔10", "E": "鸡22，兔13"},
        "correct_answer": "A",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "设鸡 x 只，兔 y 只。x + y = 35。",
            "2": "2x + 4y = 94。由第一式 x = 35-y，代入：2(35-y)+4y = 94，70+2y = 94，y = 12。",
            "3": "x = 23。鸡 23 只，兔 12 只。",
        },
        "misconceptions": {"common_wrong_1": "选C的人可能方程解错了。"},
        "step_decomposition": {"step_1": "设鸡 x 只，兔 y 只；x+y=35", "step_2": "2x+4y=94，解得 y=12", "step_3": "x=23，鸡23只兔12只"},
    },
    {
        "source": "AMC8",
        "source_year": 2016,
        "source_code": "AMC8-2016-51",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一个两位数，十位数字和个位数字之和为 11。如果把这个两位数的十位和个位数字交换，得到的新数比原数大 27。原来的两位数是多少？",
        "options": {"A": "47", "B": "56", "C": "65", "D": "74", "E": "83"},
        "correct_answer": "A",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "设十位 a，个位 b。a+b=11。",
            "2": "(10b+a)-(10a+b) = 27，即 9(b-a) = 27，b-a = 3。",
            "3": "由 a+b=11 和 b-a=3 得 b=7, a=4。原数 = 47。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能把ab算反了。"},
        "step_decomposition": {"step_1": "设十位a个位b，a+b=11", "step_2": "9(b-a)=27，b-a=3", "step_3": "a=4, b=7，原数47"},
    },
    {
        "source": "AMC8",
        "source_year": 2018,
        "source_code": "AMC8-2018-52",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "一列火车通过一座 300 米长的桥用了 20 秒，通过一座 500 米长的桥用了 28 秒。火车的速度是多少米/秒？",
        "options": {"A": "20", "B": "25", "C": "30", "D": "35", "E": "40"},
        "correct_answer": "B",
        "difficulty": 4,
        "estimated_time_sec": 120,
        "hints": {
            "1": "设火车长 L 米，速度 v 米/秒。(300+L)/v = 20, (500+L)/v = 28。",
            "2": "两式相减：(500+L)-(300+L) = 28v-20v，200 = 8v，v = 25。",
            "3": "答案是 25 米/秒。",
        },
        "misconceptions": {"common_wrong_1": "选A的人可能用桥长相减除以时间差但算错了。"},
        "step_decomposition": {"step_1": "设火车长L，速度v。(300+L)/v=20, (500+L)/v=28", "step_2": "相减：200/v=8", "step_3": "v=25米/秒"},
    },
    {
        "source": "AMC8",
        "source_year": 2023,
        "source_code": "AMC8-2023-53",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "甲乙两人一起做一项工程需要 12 天。甲单独做需要 20 天。乙单独做需要多少天？",
        "options": {"A": "20天", "B": "25天", "C": "30天", "D": "35天", "E": "40天"},
        "correct_answer": "C",
        "difficulty": 3,
        "estimated_time_sec": 90,
        "hints": {
            "1": "合做效率 = 1/12，甲效率 = 1/20。",
            "2": "乙效率 = 1/12 - 1/20 = 5/60 - 3/60 = 2/60 = 1/30。",
            "3": "乙单独做需要 30 天。",
        },
        "misconceptions": {"common_wrong_1": "选B的人可能算错通分了。"},
        "step_decomposition": {"step_1": "合做效率 1/12，甲效率 1/20", "step_2": "乙效率 = 1/12 - 1/20 = 1/30", "step_3": "乙需要 30 天"},
    },
    # ──── Bonus: 混合难题 — 5 problems ────
    {
        "source": "AMC8",
        "source_year": 2020,
        "source_code": "AMC8-2020-54",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "数列 $2, 6, 18, 54, \\ldots$ 的第 7 项是多少？",
        "options": {"A": "972", "B": "1458", "C": "2916", "D": "4374", "E": "13122"},
        "correct_answer": "B",
        "difficulty": 2,
        "estimated_time_sec": 60,
        "hints": {
            "1": "这是等比数列，公比为 3。",
            "2": "通项：aₙ = 2 × 3^(n-1)。",
            "3": "a₇ = 2 × 3⁶ = 2 × 729 = 1458。",
        },
        "misconceptions": {"common_wrong_1": "选D的人可能算成 2×3⁷。"},
        "step_decomposition": {"step_1": "识别等比数列，公比 r=3", "step_2": "通项 aₙ = 2×3^(n-1)", "step_3": "a₇ = 2×729 = 1458"},
    },
    {
        "source": "AMC8",
        "source_year": 2019,
        "source_code": "AMC8-2019-55",
        "subject": "math",
        "format": "multiple_choice",
        "question_markdown": "若 $x + y = 10$ 且 $xy = 21$，求 $x^2 + y^2$ 的值。",
        "options": {"A": "42", "B": "48", "C": "52", "D": "58", "E": "100"},
        "correct_answer": "D",
        "difficulty": 3,
        "estimated_time_sec": 60,
        "hints": {
            "1": "利用恒等式：x² + y² = (x+y)² - 2xy。",
            "2": "= 10² - 2×21 = 100 - 42 = 58。",
            "3": "答案是 58。",
        },
        "misconceptions": {"common_wrong_1": "选C的人可能算成 (x+y)²/2。"},
        "step_decomposition": {"step_1": "利用 x²+y² = (x+y)²-2xy", "step_2": "= 100-42", "step_3": "= 58"},
    },
]
