class MasteryConstants:
    INCREMENT_CORRECT = 0.3
    DECREMENT_INCORRECT = 0.15
    HINT_PENALTY_PER_LEVEL = 0.05
    DIFFICULTY_BONUS_MULTIPLIER = 0.02
    DIFFICULTY_BONUS_THRESHOLD = 5


class SelectionConstants:
    DEFAULT_TARGET_DIFFICULTY = 3
    RECENT_PROBLEM_EXCLUSION_DAYS = 7
